### ISSUE TITLE
Enhancement: Allow multiple auth scheme

### ISSUE THREAD

**Issue by widyakumara** [public-apis/public-apis#1055]
Sometime an API does not require auth to read data, but requires it to add/edit/delete data. The current columns doesn't seem to support this scenario.

**Comment by yannbertrand** [comment]
You're right.

However, from my point of view, this repo's main purpose is to list publicly readable APIs.

There are other info that we don't provide such as quotas... I'm not 100% sure we can add this kind of info without complicating the project too much. It would also require to find the info for all already listed APIs.

What do you think?

**Comment by yannbertrand** [comment]
Related to #882

**Comment by yannbertrand** [comment]
Related to #883

**Comment by Ronkiro** [comment]
Maybe should we add some short-semantic letters to it?

Like OA = OAuth, K = apikey... So a label for this would be `OA/K`
