### ISSUE TITLE
Automatically Detecting CORS Support

### ISSUE THREAD

**Issue by Mattwmaster58** [public-apis/public-apis#1129]
Hi, I was wondering if it would be possible to automatically check if CORS. As I understand it, all you need to do is check that the `Access-Control-Allow-Origin` header equals `*`. If that's the case, I think this would be relatively easy to implement.

**Comment by yannbertrand** [comment]
Hey! Thank you for the idea 🙂 

That would be great, but we don't list APIs endpoints directly. We're discussing that kind of questions and how to keep the data clear for users on #1055.
