### ISSUE TITLE
Finnhub stock API - the new kid in the block

### ISSUE THREAD

**Issue by alpha332** [public-apis/public-apis#1137]
Hi guys,

Just wanna give an update about a new free API for finance category. Finnhub is offering 60 free API calls /minute and probably the most generous of all financial data providers out there.

Their API support real-time stock prices, forex and crypto + fundamental data delivered through REST API and Websocket. Here is their docs: https://finnhub.io/docs/api

**Comment by cbedoy** [comment]
@alpha332  why don't add your API to the READ.ME

**Comment by ShillSeeker2020** [comment]
Everyone needs to be aware that alpha332 is a shill account for an employee/owner of Finnhub - Spencer Sands  

Finnhub has been shill spamming various forums including Reddit, Quora, Github, EliteTrader, Medium and other venues.   Their posts have been moderated/deleted in many places.

They have been verified as blatantly copying/redistributing data without license from places include Investors Exchange, Toronto Stock Exchange and Australian Securities Exchange, and have been sent legal cease and desist notices.

They have created multiple shill accounts and even pretend to have user conversations.  Their Github repositories are littered with unanswered/unsolved issues. 

Other Github projects have refused to deal with this sort of nonsense.

Avoid this one!

Project owners of public-apis - if you need any more information PM me.

**Comment by ShillSeeker2020** [comment]
More details about their complicity here:
https://github.com/piquette/finance-go/issues/14
https://www.reddit.com/r/algotrading/comments/in5u6x/beware_medium_guide_stock_market_apis_for_2020/
