### ISSUE TITLE
Consider adding a depreciation warning for Dark Sky weather API for 2021

### ISSUE THREAD

**Issue by mikeohara** [public-apis/public-apis#1201]
With the recent acquisition of Dark Sky by Apple: https://www.bbc.com/news/technology-52115095

The news seems to indicate that the Dark Sky API will be discontinued and no longer accepts new signups. 

> Dark Sky's API - the software that transmits information between the app and its users - will be available to customers until 2021. But the company said it will no longer sign up new subscribers.

Should there be a warning or a depreciation note for that service?

**Comment by jbrooksuk** [comment]
I'd suggest removing it altogether since they're not accepting new users.
