### ISSUE TITLE
Agify isn't available

### ISSUE THREAD

**Issue by GeekDenCode** [public-apis/public-apis#1221]
Please remove "agify" from list

**Comment by yannbertrand** [comment]
Why?

**Comment by GeekDenCode** [comment]
Okay, maybe that's because I'm from Russia
![DeepinScreenshot_select-area_20200416222724](https://user-images.githubusercontent.com/23342144/79498235-a187b600-8031-11ea-8ec8-166f146e8c85.png)

**Comment by SuperSandro2000** [comment]
Can confirm that it is available. Maybe they had a temporary outage.

**Comment by cbedoy** [comment]
Can double confirm, it's working fine.
