### ISSUE TITLE
State of public-apis

### ISSUE THREAD

**Issue by marekdano** [public-apis/public-apis#1268]
There are lots of PRs opened with "new" API which can be added to the list on README.
I'm free to help with it.

**Comment by yannbertrand** [comment]
Hey Marek, thanks for the kind message.

Unfortunately, I don't have access to the settings of the repository so I can't accept new maintainers. I'm not sur any of the current maintainers got settings access 😕 

I think @toddmotto is the only one that could help us with that as he's the org owner.

**Comment by yannbertrand** [comment]
Btw, I'll try to catch up as much as possible in October as many people want to contribute to this very list for the [Hacktoberfest](https://hacktoberfest.digitalocean.com).

**Comment by marekdano** [comment]
@yannbertrand, thanks for your reply.
Do you think that it'll be worth for fork this repo and then people can contribute to the forked one if @toddmotto won't add more maintainers?

**Comment by Darknez07** [comment]
@marekdano  Please review my request for future API for IMDB--> Help is welcome, First time posting for contribution, Correct if wrong thanks anyway Refer API_of_Imdb repo

**Comment by AnEmortalKid** [comment]
Reached out to Todd via twitter, I've found luck with that method before, let's see if it pans out again.

**Comment by yannbertrand** [comment]
Hey, Todd answered on #1401! I was wrong, he's not the owner anymore. Hopefully we can find out the new owner.

**Comment by Darknez07** [comment]
Who's the owner now?

**Comment by marekdano** [comment]
@yannbertrand any idea how we can find the new owner?

**Comment by Darknez07** [comment]
Thanks i will sure once my authentication is done

**Comment by Darknez07** [comment]
expect it in 1 hour

**Comment by yannbertrand** [comment]
@Darknez07 please don't spam about your PR. Most open source maintainers are doing it in their off time, for free.
We already have more than 200 open PRs late in here: it's a lot of work to review them.

I'm trying my best to know how we could get help. Please be patient.

**Comment by Darknez07** [comment]
So i will hold it for 1 week is that ok

**Comment by yannbertrand** [comment]
You can submit it! I just can't promise I will review it 😔

**Comment by yannbertrand** [comment]
Anyways, I'm contacting GitHub support to find a solution on the initial question.

**Comment by marekdano** [comment]
@yannbertrand Thanks for taking action to find the owner! I appreciate it!

**Comment by Darknez07** [comment]
@yannbertrand  even after a week ?

**Comment by yannbertrand** [comment]
@marekdano I'm in contact with the new owner. I will give your name to them if you're still looking to help?

**Comment by matheusfelipeog** [comment]
I'm free to help with that too, if necessary. 😄

**Comment by marekdano** [comment]
@yannbertrand yeah I'm willing to help. Are they open to reviewing PRs and merging them? I can help with it too.

**Comment by yannbertrand** [comment]
I asked to give you both access to merge PRs.

**Comment by imRohan** [comment]
Happy to help out as well! 😄

**Comment by yannbertrand** [comment]
Got no news from the owner for a month now. I've asked for news yesterday. Will let you know when something happen.

**Comment by IlanVivanco** [comment]
@yannbertrand not sure if you had any response from him/her, but I'm willing to help too.

**Comment by marekdano** [comment]
@yannbertrand any news from the owner

**Comment by PawelBorkar** [comment]
@yannbertrand @marekdano Should we create a fork of it?

**Comment by imRohan** [comment]
@PawelBorkar Not a bad idea. I'd be happy to help out with that.

**Comment by marekdano** [comment]
> @yannbertrand @marekdano Should we create a fork of it?

@PawelBorkar I thought about it before and I think owners don't care about this project anymore. It's nearly a year when I opened this issue and offered my help. 
In this stage, I'm for forking this project. There are many people who want to help.

What do you think, @yannbertrand?

**Comment by PawelBorkar** [comment]
Had you already forked it ? If not I had made an organization [free-public-apis](https://github.com/free-public-apis/free-public-apis 
) Which is a fork of it.

Let me know if you guys are interested in.

**Comment by PawelBorkar** [comment]
> @PawelBorkar Not a bad idea. I'd be happy to help out with that.

Thanks Rohan,
Here is the fork [free-public-apis](https://github.com/free-public-apis/free-public-apis) contact me if you're interested in becoming the member of the org. and then we will discuss the further tasks and plans

**Comment by yannbertrand** [comment]
I just emailed the owner to once again ask to add new maintainers for the project.

Please feel free to fork the repository. The only problem I have with that is that public-apis is insanely starred and has great SEO. Unfortunately I can't automatically redirect from this repo to another one. I've also contacted GitHub Support to make sure they don't have any solution for this kind of issues.

If we do not find a solution with the owner and GitHub Support before May 15, I will add a link to a fork at the top of the readme.

Let me know if I can be of any help with the fork, I had a few ideas to push public-apis further but needed access to the settings.

**Comment by matheusfelipeog** [comment]
> I just emailed the owner to once again ask to add new maintainers for the project.
> 
> Please feel free to fork the repository. The only problem I have with that is that public-apis is insanely starred and has great SEO. Unfortunately I can't automatically redirect from this repo to another one. I've also contacted GitHub Support to make sure they don't have any solution for this kind of issues.
> 
> If we do not find a solution with the owner and GitHub Support before May 15, I will add a link to a fork at the top of the readme.
> 
> Let me know if I can be of any help with the fork, I had a few ideas to push public-apis further but needed access to the settings.

I agree with that, looks good.

**Comment by IlanVivanco** [comment]
> I just emailed the owner to once again ask to add new maintainers for the project.
> 
> Please feel free to fork the repository. The only problem I have with that is that public-apis is insanely starred and has great SEO. Unfortunately I can't automatically redirect from this repo to another one. I've also contacted GitHub Support to make sure they don't have any solution for this kind of issues.
> 
> If we do not find a solution with the owner and GitHub Support before May 15, I will add a link to a fork at the top of the readme.
> 
> Let me know if I can be of any help with the fork, I had a few ideas to push public-apis further but needed access to the settings.

Sounds reasonable. If help is still needed, let me know.

**Comment by toddmotto** [comment]
Hope you guys find a resolution, I am still subscribed to this thread so just jumping in with a quick hello/comment.

Hopefully @paulzehetmayr  or @julian-zehetmayr can add a new maintainer as I no longer own the project/have admin rights.

Given the *112k stars* it would be great to get some of these new PRs merged in and keep the project alive. Good luck and stay well all.

**Comment by PawelBorkar** [comment]
> I just emailed the owner to once again ask to add new maintainers for the project.
> 
> Please feel free to fork the repository. The only problem I have with that is that public-apis is insanely starred and has great SEO. Unfortunately I can't automatically redirect from this repo to another one. I've also contacted GitHub Support to make sure they don't have any solution for this kind of issues.
> 
> If we do not find a solution with the owner and GitHub Support before May 15, I will add a link to a fork at the top of the readme.
> 
> Let me know if I can be of any help with the fork, I had a few ideas to push public-apis further but needed access to the settings.

 Sure :-)

**Comment by PawelBorkar** [comment]
> Hope you guys find a resolution, I am still subscribed to this thread so just jumping in with a quick hello/comment.
> 
> Hopefully @paulzehetmayr or @julian-zehetmayr can add a new maintainer as I no longer own the project/have admin rights.
> 
> Given the _112k stars_ it would be great to get some of these new PRs merged in and keep the project alive. Good luck and stay well all.

I have checked their profiles, it seems like they aren't active from so long.

Let's hope for the best :)

**Comment by yannbertrand** [comment]
Just got an answer from GitHub Support, the only thing they can do is to contact the owner on my behalf. I'm trying it, just in case.

**Comment by notkyoyo** [comment]
Same! I would be glad to help and add some of my APIs as well.

**Comment by marekdano** [comment]
@yannbertrand I have got access to merge PRs now. I think to focus on reviewing the last PRs. 
Do we have a doc for maintainers for this project that we should follow?

**Comment by imRohan** [comment]
@marekdano Do you need help with reviewing PR's? Is there any way we can get more maintainers for this project - id love to help.

**Comment by matheusfelipeog** [comment]
> @yannbertrand I have got access to merge PRs now. I think to focus on reviewing the last PRs.
> Do we have a doc for maintainers for this project that we should follow?
> Is there a chat platform that we can use to coordinate our work or bring new ideas to the project?

I also have access to merge PRs now. I'll wait for the answer

**Comment by marekdano** [comment]
> @marekdano Do you need help with reviewing PR's? Is there any way we can get more maintainers for this project - id love to help.

@yannbertrand is possible to have access for @imRohan

**Comment by yannbertrand** [comment]
> @yannbertrand I have got access to merge PRs now. I think to focus on reviewing the last PRs.
> Do we have a doc for maintainers for this project that we should follow?
> Is there a chat platform that we can use to coordinate our work or bring new ideas to the project?

Please follow the [contributing guide](https://github.com/public-apis/public-apis/blob/master/.github/CONTRIBUTING.md), it's not perfect but we can make it better together 🙂 
The "Run tests" GH Action should catch basic mistakes on most recent PRs. Please make sure to check for other PRs adding or removing the same item. You noticed we have a lot of opened PRs and some do the same. I suggest to merge the older if that's possible. If that's too complicated please open a new one or directly add/remove it in the README and mention the PR in the commit details ["Fix #XXX"/"Close #XXX"](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (that should close it).

Also keep in mind not to merge your own PRs and wait for other reviewers to take a look at them.

I would have liked to use the "Discussions" GitHub feature but I can't set it up yet. What platform would you like to use until them? Discord? Twitter?

**Comment by PawelBorkar** [comment]
Discord.

**Comment by marekdano** [comment]
I'd prefer to have Discord too.

**Comment by yannbertrand** [comment]
Please join https://discord.gg/PWSeK2CuKM

**Comment by PawelBorkar** [comment]
A Big THANKS to @yannbertrand for everything he has done to revive this repository again. From contacting GitHub support to pushing us to be added as maintainers.Together we appreciate all your work man.❤️😊

**Comment by bexdeep** [comment]
Thanks, @yannbertrand for your effort.

**Comment by Nirzak** [comment]
It's good see such effort from you guys to make this repository alive again. Waiting for my PRs to be reviewed 😄

**Comment by matheusfelipeog** [comment]
Hi @Nirzak ✋ 

> It's good see such effort from you guys to make this repository alive again. Waiting for my PRs to be reviewed 😄

We are reviewing the older PR's first and then will review the new ones. For more ref check #1604

**Comment by Nirzak** [comment]
> Hi @Nirzak ✋
> 
> > It's good see such effort from you guys to make this repository alive again. Waiting for my PRs to be reviewed 😄
> 
> We are reviewing the older PR's first and then will review the new ones. For more ref check #1604

Yeah. I know and that should be the process. There's no hurry 😀

**Comment by PawelBorkar** [comment]
@yannbertrand @marekdano @matheusfelipeog
Should we close this issue or let it be open?

**Comment by Nirzak** [comment]
> @yannbertrand @marekdano @matheusfelipeog
> Should we close this issue or let it be open?

I think it should be closed now.
