### ISSUE TITLE
Numbers api is dead

### ISSUE THREAD

**Issue by GrigoryTabachkov** [public-apis/public-apis#1280]
Hello there and thx for this repo! Very useful

Today, right before my first api-usage mini-presentation numbersapi.com 404 =)
But yesterday it works

**Comment by akinncar** [comment]
Can you try to acces again? works fine here, the url redirects to http://numbersapi.com/#42 automatically. Docs are in the main page.

**Comment by GrigoryTabachkov** [comment]
> Can you try to acces again? works fine here, the url redirects to http://numbersapi.com/#42 automatically. Docs are in the main page.

Lol today it works again
Seems I was damned at friday :)
