### ISSUE TITLE
MailboxValidator is not public? and is not free

### ISSUE THREAD

**Issue by lveillard** [public-apis/public-apis#1307]
Hello! Just to update that this api is not free. It has a free test (like all the rest of email validators) but it's a paid app.

Also the link drives directly to the webpage, no trace of any public repo

**Comment by lveillard** [comment]
Maybe it would be a nice idea to add a column to identify free/paid apis?

**Comment by yannbertrand** [comment]
I think there is a limited [free tier](https://www.mailboxvalidator.com/plans#api). Let me know if it's not accessible I'll remove it

**Comment by GeorgeWL** [comment]
it may make sense to add a new type of "Limited Free Tier"?

To my knowledge this is supposed to be only for 100% free & unlimited (or at least high enough that most won't reach the limit) though, no?

**Comment by PawelBorkar** [comment]
> 
> 
> I think there is a limited [free tier](https://www.mailboxvalidator.com/plans#api). Let me know if it's not accessible I'll remove it

It's accessible as of now.
