### ISSUE TITLE
Web Of Trust (WOT) link is dead.

### ISSUE THREAD

**Issue by r-sunny** [public-apis/public-apis#1334]
Hi,

In the antimalware section, the hyperlink associated with **Web Of Trust (WOT)** seems to be not working as expected. You will get a 404 when you try the access the link. Kindly check and correct the same.

Thanks,
Rakesh

**Comment by yannbertrand** [comment]
To replace with https://support.mywot.com/hc/en-us/articles/360024398673-3-Using-the-API

**Comment by md-yaseen** [comment]
Hi, 
I would like to work on this issue and replace the WOT hyperlink with the one provided.

**Comment by 3ng7n33r** [comment]
.take

**Comment by md-yaseen** [comment]
Okay.

**Comment by yannbertrand** [comment]
Thanks @3ng7n33r. Please be careful next time as @md-yaseen wanted to look into it.
