### ISSUE TITLE
Remove this Indian Railways (http://api.erail.in) False api #important

### ISSUE THREAD

**Issue by souvik362** [public-apis/public-apis#1360]
# Please remove this from **apiurl** list it's a false api 
### by checking it manually its look like a someone's personal website please check and remove it
* Link - [False api link](http://api.erail.in/)

**Comment by md-yaseen** [comment]
Hi, 
Indian Railways don't have an official API for public, but I found a website which that provides API and is authorized by Indian Railways.
I would like to work on this issue.
Link - https://www.affiliate.confirmtkt.com/
