### ISSUE TITLE
Let's Validate API is defunct and should be removed

### ISSUE THREAD

**Issue by t0xic0der** [public-apis/public-apis#1370]
The "Let's Validate" API has been last worked upon back in 2018. Their website and the API both give a 404 error now which means that the project is probably not maintained anymore.

**Comment by Rolv-Apneseth** [comment]
Made a pull request removing the Let's Validate API entry from the readme. #1378

**Comment by Rolv-Apneseth** [comment]
> Made a pull request removing the Let's Validate API entry from the readme. #1378

First time making a proper pull request, please let me know if I've done things correctly. Thank you

**Comment by yannbertrand** [comment]
It was great, thanks @Rolv-Apneseth and @t0xic0der

**Comment by t0xic0der** [comment]
Glad to help. :smiley:
