### ISSUE TITLE
[GitHub Action] Detect broken links

### ISSUE THREAD

**Issue by yannbertrand** [public-apis/public-apis#1408]
It would be great to check for 404 for:
- all links once a day
- the new link in a PR

**Comment by Yagueteiro** [comment]
Hi, can I do this?

**Comment by yannbertrand** [comment]
Sure, the GitHub Action can be found [here](https://github.com/public-apis/public-apis/blob/master/.github/workflows/test.yml).

The initial bash code executed by Travis was [this file](https://github.com/public-apis/public-apis/blob/master/build/main.sh) that execute some Python scripts. 
But I think the [broken links check](https://github.com/public-apis/public-apis/blob/master/build/validate_links.py) is not done since we moved to a GitHub Action.

Please keep using Python to connect everything.

**Comment by SitramSoft** [comment]
I think this issue can be closed. The action for validation of all the links from README.md is working now.

**Comment by yannbertrand** [comment]
Thanks @SitramSoft
