### ISSUE TITLE
Can we add this to awesome list repos?

### ISSUE THREAD

**Issue by luckskywalker** [public-apis/public-apis#1430]
I think this repo has his place in awesome list.

**Comment by JoshuaBehrens** [comment]
Let's have a look at https://awesomelists.top/

**Comment by yannbertrand** [comment]
Feel free to add it wherever you like!

**Comment by JoshuaBehrens** [comment]
It already is in a list somewhere in the source awesomelists.top is based on. I don't find it there :/  https://github.com/lockys/Awesome.json/pull/723 I fixed the link though
