### ISSUE TITLE
Yahoo Weather Api to be retired Feb 1, 2021

### ISSUE THREAD

**Issue by stormwild** [public-apis/public-apis#1543]
### Yahoo Weather API to be retired Feb 1, 2021

https://developer.yahoo.com/weather/

![image](https://user-images.githubusercontent.com/657249/106356245-39445f80-6339-11eb-8f3b-56278da807f0.png)

**Comment by leanh1188** [comment]
they extended the expiration time of free usage to 1. March
As of Monday, March 1, 2021, the free Yahoo Weather API will be retired.
