### ISSUE TITLE
Fork of public-apis 

### ISSUE THREAD

**Issue by PawelBorkar** [public-apis/public-apis#1571]
As there are so many Pull Requests needed to be reviewed but has remained neglected even if they do they cannot be merged due to the explicit rights of the owner of the organization. I had made a fork of this repository which you can find here [free-public-apis](https://github.com/free-public-apis/free-public-apis)

Interested volunteer can mail or PR to the repo. free-public-apis/free-public-apis

NOTE: IF YOU HAVE ANY PROBLEM REGARDING THE ORGANIZATION OR REPOSITORY MENTION ABOVE FREE FEEL TO CONTACT ME.

**Comment by marekdano** [comment]
@PawelBorkar Do you think we still need to fork this repo?

**Comment by PawelBorkar** [comment]
> @PawelBorkar Do you think we still need to fork this repo?

No.
