### ISSUE TITLE
Duplicate records should be removed.

### ISSUE THREAD

**Issue by marekdano** [public-apis/public-apis#1597]
I've found out that there are two records of the same API listed in the README.

- https://mailboxlayer.com
- https://languagelayer.com
- https://weatherstack.com

I think we should list a record of API just ones.

**Comment by yannbertrand** [comment]
Agreed.

I'd say:
- mailboxlayer stays in Data Validation
- languagelayer in Text Analysis
- weatherstack in Weather

What do you think?

**Comment by matheusfelipeog** [comment]
> Agreed.
> 
> I'd say:
> 
> * mailboxlayer stays in Data Validation
> * languagelayer in Text Analysis
> * weatherstack in Weather
> 
> What do you think?

It looks good to me.

**Comment by marekdano** [comment]
Thanks, @matheusfelipeog, and @yannbertrand. I'll update README accordingly.
