### ISSUE TITLE
Links returning 403 should be removed

### ISSUE THREAD

**Issue by marekdano** [public-apis/public-apis#1599]
Here is a list of APIs that return 403

https://ipinfodb.com/api

**Comment by vmbansal2001** [comment]
I want to contribute on this

**Comment by dilbersha** [comment]
still on?

**Comment by pawelborkar** [comment]
@dilbersha yup!

**Comment by berkaysavas** [comment]
Good

**Comment by matheusfelipeog** [comment]
I'm going to close this issue, this API is apparently working.
