### ISSUE TITLE
Regarding PR reviews

### ISSUE THREAD

**Issue by pawelbr** [public-apis/public-apis#1604]
With reference to the issue #1268 we have got the rights to review and merge the Pull Requests into the repository.
As can be seen the number of PR's are quite large. We are reviewing the older PR's first and then will review the new ones.
So it might take some time for the new PR's to be get reviewed.

Thank You.

**Comment by VChernomYA** [comment]
README.md

**Comment by pawelbr** [comment]
Congratulations to all the collaborators, we have merged a significant number of PR's in a very short time. Kudos🎉
Now the time has come to close this issue.

We would like to thanks all the contributors of the public-apis for their patience.

Thank You.
