### ISSUE TITLE
public-apis.dev domain

### ISSUE THREAD

**Issue by zaherg** [public-apis/public-apis#1612]
Hey,

I own the domain `public-apis.dev` and I would like to provide it to you as a small small contribution from me to the project, so if you like just add it as a custom domain to the repo and provide me with the info to update the DNS records.

a small attribute to `darawish.io` can be added to the readme file **(if and only if you want)**.

let me know if you like the idea or not.

Thanks

**Comment by PawelBorkar** [comment]
@zaherg Thank you so much for your humble offering/contribution. We are discussing the possibilities of it.
May we know from how long you've been owning this domain and also it's renewal date?

**Comment by zaherg** [comment]
@PawelBorkar I bought it yesterday :D when I thought about the idea so you will have at least 1y 

![image](https://user-images.githubusercontent.com/27624/113476866-d715f100-9486-11eb-8f9d-232b08500d17.png)

I am planning to keep maintaining the domain for as long as I can

**Comment by PawelBorkar** [comment]
@zaherg Thanks for the quick reply.
We'll get back to you soon :-)

**Comment by zaherg** [comment]
hey @PawelBorkar ,  I have setup a redirect on the domain to this repo, until I hear back from you.

cheers.

**Comment by PawelBorkar** [comment]
Great.
me and @matheusfelipeog are considering the domain just waiting for the other collaborators to reply or vote.

Thanks🙂

**Comment by marekdano** [comment]
I'm for it too. Thanks for your offer @zaherg! We appreciate it!

**Comment by zaherg** [comment]
Great then, you need to activate it on your repo and send me the confirmation to enable the cname record and delete the redirection, make sure to enable SSL too.

once everything is enabled, it is up to you how to build the site for the repo using github pages

**Comment by sent** [comment]
Hello,

It's a security risk to use user-provided domain names. After some time they just will move away and use the domain name for some different purposes.

Who is @zaherg and what relation he has to this repository (owner, collaborator, has rights)?

I can just throw $12 for the domain name, does that mean you will add my domain name for use in this project?

It's best to use http://public-apis.github.io/ and will keep things simple, no point to use it that domain at all.

Thanks!

**Comment by zaherg** [comment]
Hey @sent 

I agree with you people goes and things changes, but also you forget that domain ownership can be transferred from one person to another, and even expired domains can be repurchase again.

If you want to know more about me, you can use google or even visit my own site and get to know me, I don't hide behind a pseudo name, I use my real name here and everywhere.

I don't own the repo, I am not a collaborator nor I have any rights, as you know the code in this repo is licensed under MIT License, so it is easy for me to fork it and start my own Public API listing, and I even can keep mine in sync with this repo without any problem at all.

Instead I wanted to help and use my own money to help the project to flourish.

Now if the owners of the repo decided not to use it, it is up to them I don't have any power over that, its their project and I respect their decision.

My contribution is like any other contribution to this repo, but instead of adding a few code lines, I contributed with money (which is by the way another way of contribution).

**Comment by PawelBorkar** [comment]
> Hello,
> 
> It's a security risk to use user-provided domain names. After some time they just will move away and use the domain name for some different purposes.
> 
> Who is @zaherg and what relation he has to this repository (owner, collaborator, has rights)?
> 
> I can just throw $12 for the domain name, does that mean you will add my domain name for use in this project?
> 
> It's best to use http://public-apis.github.io/ and will keep things simple, no point to use it that domain at all.
> 
> Thanks!

 @marekdano @yannbertrand @matheusfelipeog 
What you guys think of this?

**Comment by sent** [comment]
@zaherg

> I agree with you people goes and things changes, but also you forget that domain ownership can be transferred from one person to another, and even expired domains can be repurchase again.

There is a github.io for this purpose.

> 
> If you want to know more about me, you can use google or even visit my own site and get to know me, I don't hide behind a pseudo name, I use my real name here and everywhere.

Does it really matter?

> 
> I don't own the repo, I am not a collaborator nor I have any rights, as you know the code in this repo is licensed under MIT License, so it is easy for me to fork it and start my own Public API listing, and I even can keep mine in sync with this repo without any problem at all.

This only confirms that the use of your domain name might be malicious in the future.

> Instead I wanted to help and use my own money to help the project to flourish.
> My contribution is like any other contribution to this repo, but instead of adding a few code lines, I contributed with money (which is by the way another way of contribution).

This isn't a contribution to this repository but a contribution to your own portfolio to later monetize this domain name.

Thanks!

**Comment by matheusfelipeog** [comment]
Thank you for wanting to contribute a domain @zaherg 🤝 

and thanks @sent, for raising these questions ✋

@PawelBorkar 
> @marekdano @yannbertrand @matheusfelipeog
> What you guys think of this?

Well, what @sent said is really a possible problem if we don't have 100% control of the domain.

Taking this into account, I think it is best to use the domain provided by github: `https://public-apis.github.io`

This would maintain control directly through the repository, without needing any external service.

It can also solve possible future problems, such as:
 
- Renew domain;
- Transfer domain to another owner when, and if, the old one leaves the project.

**Comment by zaherg** [comment]
@matheusfelipeog if any of you wants to have control over the domain I have no problem, I am willing to transfer the domain to you or @marekdano or @PawelBorkar.

**Comment by zaherg** [comment]
@sent

1. If you don't care about who I am and you think it does not matter that I am using my real name, which means any action I take will always be tied to my name, you should not have asked.

2. I don't have any intention to monetize the domain nor gain anything from it. It is just a domain which does have any real impact on my portfolio.

3. If I wanted to do any harm, I would have communicated with the owners/contributors of the repo privately so that no one can holds me accountable to my actions, instead I publicly offered my domain, which if I use in any way other than what I offer can harm my reputation not the project.

4. At the same time, if I have any intention, i wouldn't offered to transfer the domain so easily to any of the main contributors.

5. Lastly, I advice you to dive more into the OSS licenses and what they means and understand that any legal use based on the license term does not mean any intention to case any harm.

Wish you all the best 🤗

**Comment by zaherg** [comment]
I'll close the ticket as I can see you agreed to go with GitHub.io domain.

No need for all this fuzz over a domain name.

My offer to transfer the domain is still on just ping me.


Wish you all the best 🤗
