### ISSUE TITLE
WOT Api no longer offers free plans, only timed trials.

### ISSUE THREAD

**Issue by MarcoAFC** [public-apis/public-apis#1660]
Heiya!

I recently tried to use the Web of Trust (WOT) API for a small project but, despite the fact that the wiki still states they have a free plan, requesting one from the support team is received with an offer for a 40$/month plan, with 14-days trial.

This should be removed.

**Comment by omkar342** [comment]
Is this issue is still open?And if it is open can someone plz tell me how I can remove that API?

**Comment by matheusfelipeog** [comment]
Hi @MarcoAFC ✋ 

Thanks for this information.

> Is this issue is still open?And if it is open can someone plz tell me how I can remove that API?

@omkar342, Yes, still open. 
To remove the API: remove the line where it is located in the [`README.md`](https://github.com/public-apis/public-apis/blob/master/README.md) file and make a [pull request](https://github.com/public-apis/public-apis/pulls) with the removal. 😆

**Comment by omkar342** [comment]
@matheusfelipeog but wot api is still on the website of public_api.Aren't we also supposed to remove from that if it is no more free?

**Comment by matheusfelipeog** [comment]
@omkar342 This has already been resolved in #1661
