### ISSUE TITLE
Suggestion For Inspirational Quote API

### ISSUE THREAD

**Issue by George-Ogden** [public-apis/public-apis#1692]
https://inspiration.goprogram.co.uk/
Get request

**Comment by matheusfelipeog** [comment]
Hi @George-Ogden ✋ 

For an API to be listed here, it must have documentation of all its resources, as mentioned in the [Pull Request Guidelines](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md#pull-request-guidelines)
