### ISSUE TITLE
Add Notion (beta) api?

### ISSUE THREAD

**Issue by AadityaMunjal** [public-apis/public-apis#1733]
Hi

Notion recently released their own API, but it's still in beta so can I PR it?

Thanks!

**Comment by pawelbr** [comment]
@AadityaMunjal 
Yeah. 
Please go ahead.

Make sure you read the [Contributing Guide](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md) before opening a Pull Request. 🙂
