### ISSUE TITLE
Unified SDK for All APIs?

### ISSUE THREAD

**Issue by djangocaomo** [public-apis/public-apis#1780]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

**Comment by matheusfelipeog** [comment]
Hi @djangocaomo. Thanks for opening this issue. ✋ 

We have no control over the APIs listed here for creating a unified SDK for all APIs. You should search the website for the API you want to use and see if they have an SDK.
