### ISSUE TITLE
Provide a policy

### ISSUE THREAD

**Issue by jdoubleu** [public-apis/public-apis#1856]
It would be very helpful if you could provide a policy on what exactly you understand under a _"free"_ API. While the [contribution guide](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md) specifies some requirements (e.g. limit of authentication methods), it does not really explain anything beyond that.

Some "providers" might offer free (like in free beer) plans or access to data through their API, though imposing some restrictions (e.g. rate limits, granularity of data, etc.).

Additionally, some "providers" put the data, which can be collected through the API, under a license. Here, you could make some requirements for the licenses as well. Furthermore I suggest to put the license in the table.

**Comment by pawelborkar** [comment]
Thanks for opening this issue and stating the limitations of the contribution guide and also for the suggestions @jdoubleu ,
I do have some concerns regarding the APIs with the free trial plans and will also provide some policies for the same in a way that it benefits the developers the most. After drafting it will also have to get approved by the fellow collaborators   as well so it might take some time. 
@marekdano  @matheusfelipeog What are your opinions?

**Comment by matheusfelipeog** [comment]
Improving and making free tier APIs policy more explicit is good.

I just have questions about what policies we could implement to accept an API. As API's are a service that costs to keep working, it's difficult not to have limits on your free tier 🤔

**Comment by cameron187187** [comment]
[they have stole my funds !! please help this is my acount and its not in my control. xan187 is another my email is cloud901cam@protonmail.com cloud901memphis@gmail.com
transactions currently pending been goung on 10 days !!! 
![image](https://user-images.githubusercontent.com/80727796/127649819-6a847c0b-018f-486b-9dfa-0c32c783508e.jpeg)scammers address i have many i lost lots of transactions and they used get hub to steal all of them!](![image](https://user-images.githubusercontent.com/80727796/127650029-914b2633-b4e6-4175-a937-b49a650867f6.jpeg))

**Comment by codewithpom** [comment]
Why is this issue still open 😔

**Comment by matheusfelipeog** [comment]
> Why is this issue still open 😔

Because we're still going to get better. That will happen soon. 😅
