### ISSUE TITLE
ผมเป็นคนไทย (ยอมรับผมไม่เก่งภาษาเท่าไหร่ครับ)

### ISSUE THREAD

**Issue by Tohgloam** [public-apis/public-apis#1861]
ส่วนคำปรึกษาใครที่เจคแบบผมอยู่ ผมไม่ให้ข้อมูลอ้อมๆหรอกครับ ผมเป็นคนหน้าบ้านผมพูดภาษาไทย
** ติดต่อเจคหน้า+มีล่าม ผมคงช่วยอะไรได้บ้าง

**Comment by matheusfelipeog** [comment]
Please speak in English when opening an issue. 😅

If you have difficulty with English, use [google translate](https://translate.google.com.br/?sl=th&tl=en&op=translate)
