### ISSUE TITLE
TICKSEL should be taken from the list

### ISSUE THREAD

**Issue by webdevphilh** [public-apis/public-apis#1902]
the site "tichsel" has stopped their services in december 2020.

the link is found in the business chapter:
https://github.com/public-apis/public-apis#business

**Comment by matheusfelipeog** [comment]
Thanks for the info @webdevphilh, we grateful for that 🤝

**Comment by matheusfelipeog** [comment]
Removed in https://github.com/public-apis/public-apis/commit/d0e8a110478d250649ccc2575e4a077d596732ec

**Comment by Shivakumar14** [comment]
Unsubscribe
