### ISSUE TITLE
Free APIs static website

### ISSUE THREAD

**Issue by Free-APIs** [public-apis/public-apis#1919]
Using the APIs from this website and the public-apis API itself, I've created an extremely fast website with search, browse, and shuffle functionality, in addition to an intuitive and clean design.

The site is deployed and live at: [https://free-apis.github.io](https://free-apis.github.io)
And you can find the open-source repository here: [https://github.com/Free-APIs/Free-APIs.github.io](https://github.com/Free-APIs/Free-APIs.github.io)

I’d love any feedback or suggestions for improvement!

**Comment by matheusfelipeog** [comment]
Wow, this is amazing. Good job @Free-APIs, it does what you describe perfectly.

Now the community has a new website to search and find APIs for their projects. We at public-apis really appreciate that. ❤️

**Comment by pawelborkar** [comment]
It's magnificent @Free-APIs,
This is so clean, intuitive and easy to navigate.
I'm impressed.

@matheusfelipeog @marekdano We should add its link to the README.

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog @marekdano We should add its link to the README.

Maybe add a mention in `README.md` for unofficial public-apis websites?

These other websites are valid:

- [Dev Resources](https://devresourc.es/tools-and-utilities/public-apis)
- [public-apis-site](https://public-apis-site.vercel.app/)

**Comment by pawelborkar** [comment]
>Maybe add a mention in README.md for unofficial public-apis websites?

Yes, it's good to have multiple sites for a user to choose from.

**Comment by marekdano** [comment]
> > Maybe add a mention in README.md for unofficial public-apis websites?
> 
> Yes, it's good to have multiple sites for a user to choose from.

Yes, I agree with you guys! 😄

**Comment by matheusfelipeog** [comment]
Now your project is in the header of public apis @Free-APIs 🎉

See: #1985
