### ISSUE TITLE
Sponsoring this project

### ISSUE THREAD

**Issue by asim** [public-apis/public-apis#1932]
Hey all,

Firstly thanks for the great resource. I'm the new owner of [public-apis.io](https://public-apis.io) and the founder of [M3O](https://m3o.com) - a public api platform. I was wondering if there's any interest in adding sponsors to this repo and displaying logos/links to their site? We'd definitely be interested in adding M3O for such a thing.

Let me know if its of interest. I imagine many other API providers would love to do the same. It might enable some surplus cash for developers interested in doing more with the public apis stuff.

Cheers
Asim

**Comment by matheusfelipeog** [comment]
Hi @asim,

Thanks for opening this issue and taking an interest in sponsoring the Public APIs, we really appreciate that. ❤️ 

Well, I had that idea in mind to talk to the other devs who maintain public apis. So, particularly, I think it's a great idea.

As you raised this discussion, I'll take it and take it to the other devs so we can see their opinion on it. As soon as I get an answer, I'll let you know here, ok?

**Comment by matheusfelipeog** [comment]
@yannbertrand @pawelborkar @marekdano 

Guys, what do you think?

**Comment by matheusfelipeog** [comment]
Community, what do you think? Feel free to give your opinion on this 😉

**Comment by pawelborkar** [comment]
Hey @asim,
Thanks for the offer, we appreciate it.

@matheusfelipeog Yeah, I too think it's great Idea.

**Comment by marekdano** [comment]
@asim, thanks for the offer!
I agree 😄

**Comment by yannbertrand** [comment]
:wave: That would be greatly appreciated 👍

**Comment by asim** [comment]
Sounds like its a unanimous yes to sponsorship. That's great to hear. Luckily github sponsors makes this stuff pretty straight forward, it's just a case for you to decide what kind of sponsor tiers you'd want and how to feature those sponsors.

**Comment by matheusfelipeog** [comment]
A big THANKS for replying guys ❤️ 

@asim I will work on it. We collaborators will talk about how to organize this, the platform used to sponsor, the sponsor tiers and how to feature those sponsors.

This may take a few days, but we'll get these tasks done as soon as possible.

When everything is ready, I will inform you here and publicly in the repo.

**Comment by LeoLivs** [comment]
Greetings devs, wanted to know if there was an update on adding sponsors and displaying their respective logos/links. Thanks in advance.

**Comment by asim** [comment]
Still very much interested in sponsoring and getting our company logo from m3o.com in the project. Our goals are very much aligned and we want to help the cause.

**Comment by LeoLivs** [comment]
How would I find sponsors to support this repo? Once I have that list, do I put their info in the documentation file?

**Comment by matheusfelipeog** [comment]
Hi @LeoLivs and @asim ;)

Thanks for having and continuing your interest in sponsoring the Public APIs project. <3

Well, [as I said earlier](https://github.com/public-apis/public-apis/issues/1932#issuecomment-898970205), I would be responsible for this work, so I'll explain why we haven't started this yet:

The long wait time is basically motivated by the fact that it is extremely difficult to talk and get a response from the current owner of the public-apis organization. The current owners and their representative (@apilayer-admin) are extremely inactive in the organization and this repository. This makes it even more difficult.

We, currently active maintainers, would need to have access to organization and repository settings, which are currently only available to the owner, in order for us to be able to activate the sponsor button and make this feature public.

I've already considered using third-party platforms, which are normally used to sponsor open source projects as well, such as [open collective](https://opencollective.com/), and informing that we accept sponsorship on README.md (without the sponsor button). This would make it easier for us to start working with sponsorship.

But note that the current owner's lack of response affects not only the sponsorship functionality, but the project as a whole. As maintainers, we have some limitations, defined by GitHub, when we want to execute some of our ideas to improve the project for the community.

So to avoid any possible problems I'm waiting for a response from the owner so that we can improve the project with more control and safety for the community.

I really apologize for this delay, I am actively trying to resolve this without harming this amazing community. As soon as I get it, I will publicly inform you here in the issue and in the project.

**Comment by asim** [comment]
Thanks for the detailed response! It's unfortunate you don't own the org. There's definitely alternative approaches but I think it's ok to wait for a response from the owner. I may ping again in January. Other potential options are just sponsor link to an Ethereum wallet 😀

**Comment by codewithpom** [comment]
@asim yes and I am even experienced in Blockchain and web3 stuff.

**Comment by asim** [comment]
Continuing on with this discussion. Since it may not be possible to use github sponsors. Can we try something else? Like perhaps https://opencollective.com/

**Comment by codewithpom** [comment]
Looks good

**Comment by pawelborkar** [comment]
Hey @matheusfelipeog,
I think we've waited for so long for the response from the current admin/owner of the project. and unfortunately it seems that they didn't even care to respond back to us. So in my opinion we should go with the [Open Collective](https://opencollective.com/) way for enabling a way for the individuals and orgs who are interested in sponsoring the project.

@marekdano @yannbertrand What you guys think?

**Comment by matheusfelipeog** [comment]
Yes, you're right. We can try to use Open Collective

I'll take care of that and come back soon with more information. 🚀

**Comment by dr-suhadalishaheed** [comment]
Er #[]()

**Comment by matheusfelipeog** [comment]
Just an update: I'm awaiting approval from the Open Source Collective

**Comment by matheusfelipeog** [comment]
The Open Source Collective fiscal host has approved the application of Public APIs:

![image](https://user-images.githubusercontent.com/50463866/152057719-8c237d4c-a159-465f-80a5-bb7f698c3857.png)

It is now possible to be a backer and sponsor of the project. See more information at: https://opencollective.com/public-apis

Soon, a section will be added to the `README.md` to inform everyone who visits the repository.

**Comment by asim** [comment]
We at [M3O](https://m3o.com) are happy to officially be the first sponsor!

The logo can be found here https://raw.githubusercontent.com/m3o/m3o/main/images/m3o.png

**Comment by matheusfelipeog** [comment]
@asim Thank you very much and congratulations on being the first sponsor of public APIs ❤️ 

It's really a great idea to integrate the public apis available here in M3O, it will be very useful for us developers.

> Logo below to be linked to https://m3o.com
> 
> ![m3o-logo-black](https://user-images.githubusercontent.com/17530/152060453-37ffe116-660b-4ff4-809a-8a9c222a90e3.png)

I'm going to add the M3O logo to our readme.md, would you like to add the slogan and/or a brief description about M3O?

What do you think about using what is shown on the homepage?

```
The fastest way to integrate APIs into any product
```

and/or

```
Explore, discover and consume public APIs as simpler programmable building blocks all on one platform for a 10x developer experience.
```

Or do you prefer it to be just the logo?

**Comment by asim** [comment]
Yes please do also add the slogan and description thanks!

**Comment by matheusfelipeog** [comment]
> Yes please do also add the slogan and description thanks!

Done ✔

**Comment by asim** [comment]
Thank you. Someone mentioned the logo has a transparent background and doesn't play well with dark mode. Here's one with a white background. Sorry for the inconvenience.

![m3o-boxed-black](https://user-images.githubusercontent.com/17530/152122228-fb1a4a45-6109-4205-af16-b1cc3afa9728.jpg)

**Comment by asim** [comment]
Logo has a transparent background so doesn't play well with dark mode. Let me give you this one instead. Sorry for the inconvenience. 

![M3O Logo](https://user-images.githubusercontent.com/17530/152123159-e64645f8-4e60-4fde-afc9-8ada30c45309.png)

**Comment by yannbertrand** [comment]
It's now possible to use different images for white & dark modes using GitHub markdown :)

https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by asim** [comment]
Whoa, I'm way behind in the times :D 

Then I'll provide the white logo also

![m3o-logo-white](https://user-images.githubusercontent.com/17530/152129134-d83100d7-1e44-4739-b7fd-7eafb22bf4ef.png)

**Comment by yannbertrand** [comment]
Done in #3042 

![image](https://user-images.githubusercontent.com/5855339/152138480-bdba7b76-4bf8-4268-92e6-89253648e272.png)
![image](https://user-images.githubusercontent.com/5855339/152138507-36182b6e-ce5c-4aa4-83a3-a531062b0692.png)

**Comment by yannbertrand** [comment]
Thanks again for the sponsorship! I'll close the issue now.

Please feel free to open a new issue when needed.
