### ISSUE TITLE
Change Bible API from Portugese to English

### ISSUE THREAD

**Issue by digitalblossom** [public-apis/public-apis#1939]
Given the repo is in English, it would make sense to link to the English version of the Bible API. It's a little hidden in the dropdown menu

https://bibleapi.co/en

**Comment by pawelborkar** [comment]
Hey @digitalblossom.
Thanks for opening this issue, we appreciate your effort.

Would you like to go ahead and make a PR for the same?

**Comment by digitalblossom** [comment]
Hi @pawelborkar, i just created a pr. I'm rather new to commits so please let me know if I did something incorrectly

**Comment by pawelborkar** [comment]
> Please let me know if I did something incorrectly

It's perfect 😊
