### ISSUE TITLE
Gcash

### ISSUE THREAD

**Issue by Eastwestbanker** [public-apis/public-apis#1947]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

**Comment by matias904** [comment]
Bzzz

**Comment by Eastwestbanker** [comment]
What

**Comment by xan187** [comment]
My account xan187 is compromised over the past month everything has not been me. Ppl/hackers have email Apple ID and iTunes. I'm turn to stop it but it could be internal. With info like ssn. Please don't help on anything posted with this account unless directed towards information retrieval! I will continue to look at this and email for info if anyone can help

**Comment by xan187** [comment]
My account xan187 is compromised over the past month everything has not been me. Ppl/hackers have email Apple ID and iTunes. I'm turn to stop it but it could be internal. With info like ssn. Please don't help on anything posted with this account unless directed towards information retrieval! I will continue to look at this and email for info if anyone can help

**Comment by Eastwestbanker** [comment]
Thanks
