### ISSUE TITLE
Am new to coding!

### ISSUE THREAD

**Issue by tonymukiibi** [public-apis/public-apis#1957]
I need help to start up.
I want to start from scratch 
I want to develop a Bible app.
I have little coding background 

Thanks

**Comment by NerdlyTei** [comment]
You can start with c#

**Comment by Whitedevil5833** [comment]
**You Can Start With C**

**Comment by Rom1deTroyes** [comment]
Start by writing some tests : Units test are always welcomed in projects.

**Comment by matheusfelipeog** [comment]
Hi @tonymukiibi, welcome to world of programming 👨‍💻 🌎 

You can get started with FreeCodeCamp courses on the [website](https://www.freecodecamp.org/) or on the [youtube channel](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ).
