### ISSUE TITLE
AiP

### ISSUE THREAD

**Issue by hanlay123** [public-apis/public-apis#1975]
curl "https://api.cryptomkt.com/v1/order"
   -H "X-MKT-APIKEY:  <tu api key>"
   -H "X-MKT-SIGNATURE:  <mensaje generado y firmado>"
   -H "X-MKT-TIMESTAMP:  <timestamp de la llamada>"
   -X POST

**Comment by cameron187187** [comment]
Curl not working 


Sent from Yahoo Mail for iPhone


On Saturday, August 21, 2021, 5:35 AM, hanlay123 ***@***.***> wrote:




curl "https://api.cryptomkt.com/v1/order"
-H "X-MKT-APIKEY: "
-H "X-MKT-SIGNATURE: "
-H "X-MKT-TIMESTAMP: "
-X POST

**Comment by cameron187187** [comment]
Sent from Yahoo Mail for iPhone

**Comment by cameron187187** [comment]
Hello its cameron

**Comment by cameron187187** [comment]
Hi it’s cameron


Sent from Yahoo Mail for iPhone


On Sunday, August 22, 2021, 5:23 AM, Pawel Borkar ***@***.***> wrote:




Closed #1975.

**Comment by cameron187187** [comment]
Hi I’m lost I’m sorry. You wanted me to reply by email?


Sent from Yahoo Mail for iPhone


On Sunday, August 22, 2021, 5:24 AM, Molly Prather ***@***.***> wrote:

Hi it’s cameron


Sent from Yahoo Mail for iPhone


On Sunday, August 22, 2021, 5:23 AM, Pawel Borkar ***@***.***> wrote:




Closed #1975.
