### ISSUE TITLE
LekDfUuQFRqN3Tm9eMJZq5riZUb6FkuXVE

### ISSUE THREAD

**Issue by matias904** [public-apis/public-apis#1978]

**Comment by cameron187187** [comment]
Hi I’m willing to do whatever I’m just lost sorry


Sent from Yahoo Mail for iPhone


On Sunday, August 22, 2021, 5:23 AM, Pawel Borkar ***@***.***> wrote:




Closed #1978.

**Comment by pawelborkar** [comment]
>Hi I’m willing to do whatever I’m just lost sorry

Please stop replying to these issues and PR, you are spamming it.

If you want to contribute by making a PR or creating a genuine issue feel free to do so but for God sake please stop commenting unnecessary things into the issues and PR sections. 

I guess you are watching this repository and didn't know how GitHub work so I encourage you to watch some GitHub tutorials on YouTube. 

Just stop spamming dude, we are volunteering this in our free time and your acts makes us pissed off. 

No offense.

**Comment by cameron187187** [comment]
Ok damn didn’t know.I appreciate the help. Last thing I wanna be doing I’ll take the time to figure out basics.

**Comment by pawelborkar** [comment]
Thanks v@cameron187187
