### ISSUE TITLE
NumValidate does not work ?

### ISSUE THREAD

**Issue by erwanvivien** [public-apis/public-apis#1981]
Hello,

Just tried to use NumValidate as a test, with the default example they have on [numvalidate website](https://numvalidate.com/)
```bash
curl https://numvalidate.com/api/validate?number=12015550123
```

And it gave
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at numvalidate.com Port 80</address>
</body></html>
```

This address is not working too [https://numvalidate.com/api/validate](https://numvalidate.com/api/validate)

**Comment by matheusfelipeog** [comment]
Thanks for letting us know about this. @erwanvivien 

This API is not working, I will remove it.
