### ISSUE TITLE
Inactive PRs must be closed and their APIs added

### ISSUE THREAD

**Issue by matheusfelipeog** [public-apis/public-apis#2002]
There are many inactive PRs that have already been revised and with their APIs according to our addition criteria. These PRs are just waiting for some correction that was requested by one of the maintainers, and as they are inactive PRs, they will likely not be done.

Inactive PRs must be closed and their APIs added if they still meet our criteria.

Maintainers can add the APIs of these PRs in their respective sections directly on the master branch (since they have already been reviewed previously).

Contributors can open new PRs to add APIs of inactive PR.

Consider as inactive PR those that have no reply from their creator for more than 1 month.

To facilitate tracking, please mark the inactive PR in the new PR.

**Comment by webdevrahul** [comment]
Hey

**Comment by vamagithub** [comment]
Can i work on this issue.

**Comment by priyanshm07** [comment]
Are there any open issues?
@matheusfelipeog would like to work on them.

**Comment by CipherGirl** [comment]
@matheusfelipeog Hey! I have raised some PRs. It would be great to have your feedback and your consideration about 'hacktoberfest-accepted' label :)

**Comment by megamayoy** [comment]
@matheusfelipeog I wanna contribute during the Hacktoberfest. Can I work on this inactive PR https://github.com/public-apis/public-apis/pull/1678 ?

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog Hey! I have raised some PRs. It would be great to have your feedback and your consideration about 'hacktoberfest-accepted' label :)

Excellent @CipherGirl, we will review all PRs as soon as possible. Note that there are many ;)

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog I wanna contribute during the Hacktoberfest. Can I work on this inactive PR #1678 ?

Very good @megamayoy. Of course you can, you can create a new PR for any inactive PR as I described at the beginning of this issue:

> Consider as inactive PR those that have no reply from their creator for more than 1 month.

**Comment by OscarRG** [comment]
Hey @matheusfelipeog i show that the Bible API is inactive and i created a PR to remove it from the list :) [PR](https://github.com/public-apis/public-apis/pull/2176/files). I added also a Harry Potter API to fetch the characters: [PR](https://github.com/public-apis/public-apis/pull/2174)

**Comment by matheusfelipeog** [comment]
All inactive PRs have already been reviewed, added or rejected. A big THANK YOU to everyone who helped us with this issue ❤️
