### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Ciscoflash** [public-apis/public-apis#2048]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

how do I get sample API for testing as a beginner

**Comment by Lucifer0440** [comment]
How how do I get sample API for testing as a beginner

**Comment by matheusfelipeog** [comment]
@Ciscoflash @Lucifer0440 

You can choose one of the [APIs listed in README.md](https://github.com/public-apis/public-apis#readme) and read its documentation. All APIs listed here can be used for free on some tier.

You can also see how to create your own through the FreeCodeCamp course, [Back End Development and APIs](https://www.freecodecamp.org/learn/back-end-development-and-apis/).
