### ISSUE TITLE
Changing Cryptocurrency category name to Blockchain

### ISSUE THREAD

**Issue by daviddavo** [public-apis/public-apis#2178]
While the blockchain is mainly known for cryptocurrency and decentralized finance, it has a lot of applications like decentralized autonomous organizations, NFT marketplaces, etc.

For this reason, there are some APIs like #2179 that are focused on studying other aspects of the various blockchain apart from cryptocurrencies.

What do you think?

**Comment by pawelborkar** [comment]
Thanks @daviddavo for opening this issue and providing a suggestion. We appreciate it. 
But I think changing the category name of Cryptocurrency to the Blockchain may result into some confusion while searching for the APIs on Cryptocurrencies for beginners.
So, to resolve this issue we'll be creating a new category for the Blockchain which will explicitly contains the projects based on blockchain technology other than cryptocurrencies. In this way we can have both eliminating any possibility of confusions that may be occur.

Thanks for bringing it in front of us.😊

**Comment by pawelborkar** [comment]
Closing this issue. ref #2189 

Feel Free to share your opinion @daviddavo

**Comment by Priyojone** [comment]
New catagorius
