### ISSUE TITLE
Projects based on Blockchain Technology other than Cryptocurrencies should be added to the Blockchain Category

### ISSUE THREAD

**Issue by pawelborkar** [public-apis/public-apis#2189]
- Projects based on Blockchain Technology other than Cryptocurrencies should be added to the Blockchain Category
- Projects which uses blockchain technology and are Cryptocurrencies should be added to the Cryptocurrency category only and not to the Blockchain category.
- No API should be added to both the categories. If it's crypto then add it to cryptocurrency if it's not and uses blockchain technology then add it to the Blockchain category.

Thanks

**Comment by RenatoLopes771** [comment]
Maybe we should consider having Blockchain and Blockchain (Cryptocurrency)?

**Comment by pawelborkar** [comment]
> Maybe we should consider having Blockchain and Blockchain (Cryptocurrency)?

Nope. It's better to have a separate category for both of them with the proposed naming convention.

**Comment by megamayoy** [comment]
Could you please assign this to me?

**Comment by NIKU-SINGH** [comment]
@pawelborkar could you check this PR ?
https://github.com/public-apis/public-apis/pull/2581

**Comment by A3lli0t** [comment]
Can anyone please guide me on how to do this? I'm a newbie.

**Comment by matheusfelipeog** [comment]
This issue has now been resolved. A big THANK YOU to contributors <3
