### ISSUE TITLE
UI Upgrade for kanye.rest API

### ISSUE THREAD

**Issue by sayonnnnnn** [public-apis/public-apis#2427]
The public API page for kanye.rest can use a UI upgrade as well which would be a bit more funky and aesthetic to Kanye West. #2107

**Comment by matheusfelipeog** [comment]
@sayonnnnnn Thanks for opening this issue ;)

We are not maintainers of this API. You must indicate an update to the UI of the page in their repository: https://github.com/ajzbc/kanye.rest
