### ISSUE TITLE
Remove catAPI from Animals

### ISSUE THREAD

**Issue by hippyaki** [public-apis/public-apis#2446]
Here is the updated API Doc of catAPI, https://github.com/ThatCopy/catAPI/wiki/Docs

 But the API server is returning a 404 error. Might as well remove nonfunctional API sites.

**Comment by matheusfelipeog** [comment]
This is fixed in: #2448

**Comment by hippyaki** [comment]
@matheusfelipeog Clear the PRs please, I'm willing to commit to separate PRs for other updates.

Like, this #2399

**Comment by matheusfelipeog** [comment]
> @matheusfelipeog Clear the PRs please, I'm willing to commit to separate PRs for other updates.
> 
> Like, this #2399

Please wait, note that there are many PRs to review and we will do this as soon as possible.

Old ones are revised first. This will be revised soon.
