### ISSUE TITLE
Why are the PRs not being updated for the last few days?

### ISSUE THREAD

**Issue by hippyaki** [public-apis/public-apis#2558]
Just need a quick update. Close this issue, immediately after replying.

@pawelborkar

**Comment by matheusfelipeog** [comment]
Hi @hippyaki ;)

> Why are the PRs not being updated for the last few days?

Many PRs are reviewed and merged practically every day. Just see our [commit history](https://github.com/public-apis/public-apis/commits/master).

Some recent PRs can be revised first as the maintainer deems necessary. The reason for this may vary.

For example: I review some PRs whose contribution is an update, removal or correction of some API already listed. Also, I sometimes revise when there is a duplicate PR.

Knowing this now, I ask you to wait until your PR is reviewed, please. Note that there are many open PRs and all will be reviewed as well. 😅
