### ISSUE TITLE
Icons8 API is a PAID service

### ISSUE THREAD

**Issue by hippyaki** [public-apis/public-apis#2807]
Current Link - https://icons8.docs.apiary.io/#reference/0/meta
The link provided in the present version redirects to an old version of API, which does not work.

The updated section of API is in [link](https://icons8.github.io/icons8-docs/#Icons%20API), which has its endpoint details in [link](https://icons8.github.io/icons8-docs/api/search-engine/)

But then it turns out, it's not the original website.

Original API documentation - https://developers.icons8.com/docs. It has many other services other than icons.
All of which is available on a trial period. Not available for free. [Link](https://developers.icons8.com/pricing)

Haven't seen any API key on the https://developers.icons8.com/api-keys after filling the Typeform as well

There is a subsidiary `omg-img`, which is free.
Free Icons API from Icons8 - http://img.icons8.com/

Does anybody want to take this up?

**Comment by c6z3h** [comment]
I can give it a shot. Thanks for digging into it!

**Comment by hippyaki** [comment]
@c6z3h Wait for approval from a maintainer. Then you can make the required changes.

**Comment by matheusfelipeog** [comment]
This looks good to me. Thank you so much for checking and letting us know this @hippyaki ❤️ 

I will review the PR.
