### ISSUE TITLE
Update required in SwiftKanban API Doc Link

### ISSUE THREAD

**Issue by hippyaki** [public-apis/public-apis#2819]
Current Link - https://www.digite.com/swiftkanban/

This link redirects to the home page, but no documentation or reference to the APIs.

Correct Link - https://www.digite.com/knowledge-base/swiftkanban/article/api-for-swift-kanban-web-services/#restapi

This link has proper documentation on the API.

Does anybody want to take this up?

**Comment by matheusfelipeog** [comment]
The API reference is at the footer of the page, but linking the documentation directly is better and preferable.

Thank you very much for one more check @hippyaki <3

**Comment by JadenLeake333** [comment]
May I be assigned this issue?

**Comment by hippyaki** [comment]
@JadenLeake333 You can open a PR, and the maintainer will link this issue to the PR.
