### ISSUE TITLE
Am I allowed open PR for fixing name on an old API ?

### ISSUE THREAD

**Issue by sharadcodes** [public-apis/public-apis#2899]
I was looking on a site which used this site for listing APIs and saw that the name of my API was still old.
Can I update and open a PR.

Its under text analysis section Sentium is the name SENTIM is the new name.
Link: https://sentim-api.herokuapp.com/

**Comment by matheusfelipeog** [comment]
Oh right @sharadcodes. Thank you for letting us know this. ;)

Can you open a PR to update to the new name and link to this issue please?

**Comment by sharadcodes** [comment]
Will do it, thanks for answering

**Comment by pawelborkar** [comment]
Hey @sharadcodes,
Looks you got the answer for this issue.
Closing this as of now but do mention it whenever you open a PR regarding the context you mentioned above.

Thanks.
