### ISSUE TITLE
Indeed API

### ISSUE THREAD

**Issue by manjula-guneratne** [public-apis/public-apis#2927]
Hi!,

Just wanted to let you know the Indeed API end points are depreciated and it cannot be used anymore.

https://developer.indeed.com/docs/publisher-jobs/

**Comment by pawelborkar** [comment]
Thanks for the update @manjula-guneratne. Would you like to make a PR on this?

**Comment by manjula-guneratne** [comment]
Yes, I will submit one today.

**Comment by pawelborkar** [comment]
Ref. #2933
