### ISSUE TITLE
transfer.sh website seems to be no longer functioning

### ISSUE THREAD

**Issue by adriangohjw** [public-apis/public-apis#2931]
Under Cloud Storage & File Sharing (https://transfer.sh/)

**Comment by pawelborkar** [comment]
Thanks for the update @adriangohjw 😊

**Comment by matheusfelipeog** [comment]
@adriangohjw and @pawelborkar I believe it was a momentary problem, as it is working normally here: 

ref 1: home page
![image](https://user-images.githubusercontent.com/50463866/144130216-70d87f41-a962-4e99-8cc6-553d3497853d.png)

ref 2: Upload using cURL
![image](https://user-images.githubusercontent.com/50463866/144130079-d4c6c6db-98c2-4b3b-96d7-fbb846525b32.png)

ref 3: Upload from web
![image](https://user-images.githubusercontent.com/50463866/144129736-3240b881-d4ec-437a-9beb-0c94c97aa7aa.png)

**Comment by adriangohjw** [comment]
@matheusfelipeog thanks for pointing it out. I just tried to VPN to another country and it works, maybe its just banned in my country for some unknown reason.

@pawelborkar sorry so much for the false alarm

**Comment by pawelborkar** [comment]
@adriangohjw You're right. It's not working in my country as well. As I had tried to go the web address before removing it from the list and found that the link is not working.

@matheusfelipeog It's better to have APIs which are globally accessible and not in a specific geographical region as it may cause issues or an unwanted struggle for junior developers or hobbyists from the region in which the site is not working.
