### ISSUE TITLE
New API for test data

### ISSUE THREAD

**Issue by munzzz5** [public-apis/public-apis#2941]
Hi was wondering if I can add the "this for that" API as it is a great way for first time API consumers. 

Here's the link (it returns 2 types of response formats (Text [an English sentence], and Json with two key values[this for that])

http://itsthisforthat.com/api.php

**Comment by matheusfelipeog** [comment]
Hi @munzzz5 😄 

Yes, you can add this API to the list ;)

Open a PR and send it with this addition and I will review it

**Comment by munzzz5** [comment]
Great!

This is my first issue in life. Am I supposed to just fill up the table with relevant links or shall I post the python code example?

I have read the docs. But I'm still unsure. 

Thank you!

**Comment by matheusfelipeog** [comment]
@munzzz5 You just need to put the link and other API information on a new line in the table, following the pattern of those already listed.

Example:

For this link https://itsthisforthat.com/api.phpz, you should add something similar to this in the table in the Test Data section:

```
| [ItsThisForThat](https://itsthisforthat.com/api.php) | <A description> | No | Yes | Unknown |
```

**Comment by munzzz5** [comment]
hey there 

i have another API called bored API which is essentiallly similar and fits into the same category of test data.

Kindly check it out and let me know if i should go for PR.

Thanks!
http://www.boredapi.com/

**Comment by matheusfelipeog** [comment]
> hey there
> 
> i have another API called bored API which is essentiallly similar and fits into the same category of test data.
> 
> Kindly check it out and let me know if i should go for PR.
> 
> Thanks! http://www.boredapi.com/

This API is already listed here. See in Development section.
