### ISSUE TITLE
This means Lakota Family, in Native American. It's the tribe I've descended from. It's also the poorest county in the United States. I don't live there but all of my family does. It's extreme poverty on the Pine Ridge Reservation. So I want to creat a crypto currency that I can make profitable for them. The least I can do for them kids and the ones who managed to make it through blizzards, wars, and sicknesses. If anyone can assist me in creating this crypto it will be gratefully appreciated. I'm a rookie myself in the crypto world but I only get to live once!

### ISSUE THREAD

**Issue by Swhistler1** [public-apis/public-apis#2944]
This means Lakota Family, in Native American. It's the tribe I've descended from. It's also the poorest county in the United States. I don't live there but all of my family does. It's extreme poverty on the Pine Ridge Reservation. So I want to creat a crypto currency that I can make profitable for them. The least I can do for them kids and the ones who managed to make it through blizzards, wars, and sicknesses. If anyone can assist me in creating this crypto it will be gratefully appreciated. I'm a rookie myself in the crypto world but I only get to live once!

__Originally posted by @Swhistler1 in https://github.com/Iktomi-ink/demo-repository/issues/1__

**Comment by codewithpom** [comment]
@Swhistler1 just create a 10 line solidity code and deploy to the ethernum network and a token will be created and that's it😀
