### ISSUE TITLE
Help Required: API not documented

### ISSUE THREAD

**Issue by 0x0is1** [public-apis/public-apis#2951]
I use these few APIs for world political data analysis provided by Lowy Institute, Australia

+ `https://power.lowyinstitute.org/data/2020.json`
+ `https://power.lowyinstitute.org/countries.json`
+ `https://power.lowyinstitute.org/world.json`
+ `https://power.lowyinstitute.org/network-power.json`

Their reports and data are also used IMF and other UN foundations.
But they don't have proper documentation so i can't add one direct link in repo. Please suggest me what should i do?

**Comment by 0x0is1** [comment]
(Expecting replies since 1931.)

**Comment by matheusfelipeog** [comment]
@0x0is1 As stated in the contribution guide, it's necessary for the API to have official documentation in order to be added to the list. And as this API doesn't meet this requirement, unfortunately, it's not possible to add it.

**Comment by 0x0is1** [comment]
That's quite sad😓 but okay..!

**Comment by matheusfelipeog** [comment]
> That's quite sad😓 but okay..!

@0x0is1 I thought of something. 🤔

You can create a repository here on github and create unofficial documentation for this API. So I can accept for listing.

You should document and explain what each of these endpoints is for so others can easily use them.

What do you think?

**Comment by matheusfelipeog** [comment]
Some examples you can follow:

- https://github.com/btcid/indodax-official-api-docs/blob/master/Public-RestAPI.md
- https://github.com/thundercomb/poetrydb#readme
- https://github.com/CrossRef/rest-api-doc

**Comment by 0x0is1** [comment]
Thanks for the amazing suggestion. Working on it. :)

**Comment by matheusfelipeog** [comment]
Okay, I'll be waiting. Request my review when you're done, please. ;)

**Comment by 0x0is1** [comment]
Resolved in #2982,
