### ISSUE TITLE
Host in validate_links.py

### ISSUE THREAD

**Issue by ChaseDurand** [public-apis/public-apis#2960]
Hello!

Why is www stripped from the host in validate_links.py?
<pre>
if host[:3] == 'www':     
    host = host[4:]
</pre>

The host header does not forbid www, and some sites return 40x errors when this is stripped out in the request (examples include https://www.fishwatch.gov/developers and https://www.petfinder.com/developers). I found 144 links out of the 1409 invalid links that return status 200 when the correct host header is used.

Is there a reason behind stripping www from the header? If not, I can create a pull request to update the code.

Thank you!

**Comment by matheusfelipeog** [comment]
Hi @ChaseDurand, thanks for opening this issue. ;)

I'll check that out, but yes, there's a reason I removed it. Apparently it's a requirement for Cloudflare. 

See the discussion in PR that implemented this at: #2409

**Comment by matheusfelipeog** [comment]
@ChaseDurand I checked this problem today and I see you're right. Keep the www. on the host decreases 4xx errors.

You can open a new PR to update the script.

When finished, request my review, please.

**Comment by ChaseDurand** [comment]
Hello @matheusfelipeog! My apologies on the delay. By the time I got around to working on this I saw that you had already implemented a solution.

I'll close the issue. Thank you :)
