### ISSUE TITLE
Remove Apple Music (Paid)

### ISSUE THREAD

**Issue by r0hin** [public-apis/public-apis#3016]
Apple Music API requires a signed developer key which costs $100 annually.

**Comment by matheusfelipeog** [comment]
Hi @r0hin, thanks for opening this issue and letting us know about it. ;)

Can you give me more information and/or send me a link containing this information so I can verify it, please?

I didn't find anything similar in the documentation

**Comment by r0hin** [comment]
Sure!

To send requests, I believe you need a [key](https://developer.apple.com/documentation/applemusicapi/getting_keys_and_creating_tokens) which you can [create](https://help.apple.com/developer-account/#/devcdfbb56a3). 

However, when trying to create a key in [Certificates, Identifiers, and Profiles](https://developer.apple.com/account/resources), the following screen is shown:

![image](https://user-images.githubusercontent.com/46874702/150285499-63cf3301-30f2-4b81-9b29-ea380d7a5dc7.png)

Let me know if you find the same.
Thanks!

**Comment by matheusfelipeog** [comment]
Thanks for the new information. I checked and it seems to me that you are right.

It's the first time I've seen a company charge a developer to have access to this type of resource 🤣

ref 1: https://developer.apple.com/support/enrollment/
ref 2: https://developer.apple.com/programs/enroll/
![image](https://user-images.githubusercontent.com/50463866/150291794-1e4180a7-f551-412a-bd60-ca9522068bdb.png)

I will remove it from the list now.

**Comment by matheusfelipeog** [comment]
Done ✅

**Comment by dr-suhadalishaheed** [comment]
- [ ] - - [ ] Remove 3016
