### ISSUE TITLE
Add oyyi 

### ISSUE THREAD

**Issue by coder9118** [public-apis/public-apis#3022]
Thanks for looking to open an issue for this project.
oyyi is free to use API for image/video conversion , optimization , pdf optimization and thumbnail generation.
If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

**Comment by matheusfelipeog** [comment]
Hi @coder9118 ;)

Can you open a PR to add the API link so we can review it, please?

**Comment by matheusfelipeog** [comment]
I did some tests on oyyi and apparently your API is not working.

Some endpoints have a return similar to this:

```json
{"status":"failed","message":"Original File has been deleted from server"}
```

and others have no return.

Therefore, I will close this issue.

**Comment by coder9118** [comment]
Can I have the endpoint you have tested? Have you seen the docs before making request to API [](https://oyyi.xyz/docs/1.0/overview)

**Comment by matheusfelipeog** [comment]
I did some new tests and now I was able to use it correctly. Sorry for the inconvenience

This project was added in the commit: https://github.com/public-apis/public-apis/commit/34b275598d88b5d006c46eda0dddac765a107e3d

**Comment by coder9118** [comment]
Change cors to yes.

**Comment by matheusfelipeog** [comment]
Done ;)
