### ISSUE TITLE
Remove Goodreads API

### ISSUE THREAD

**Issue by JJTech0130** [public-apis/public-apis#3027]
The Goodreads API has been shut down, see https://help.goodreads.com/s/article/Does-Goodreads-support-the-use-of-APIs.

It should be removed from the list, or marked, to avoid confusion.

**Comment by matheusfelipeog** [comment]
Oh right @JJTech0130. Thanks for letting us know, I will remove it from the list.

**Comment by matheusfelipeog** [comment]
Done ✅
