### ISSUE TITLE
Add Free Url Shortener

### ISSUE THREAD

**Issue by Ulvis** [public-apis/public-apis#3097]
Possible add ulvis.net url shortner [API](https://ulvis.net/developer.html)  in the list.

**Comment by matheusfelipeog** [comment]
Hi @Ulvis ;)

This API seems valid, I'll add it to the list.

Thank you very much for your contribution <3

**Comment by matheusfelipeog** [comment]
Done ✔

**Comment by jak1110p0** [comment]
> เป็นไปได้ที่จะเพิ่ม ulvis.net url shortner [API](https://ulvis.net/developer.html) ในรายการ
