### ISSUE TITLE
Show progress as the file is being processed

### ISSUE THREAD

**Issue by faiqali1** [public-apis/public-apis#3111]
Currently when the script is being run it looks like this

![image](https://user-images.githubusercontent.com/74228240/159702829-ee2a0d33-76f4-49a3-a2ae-d6fbdbcbad3f.png)

It is very hard to know how much has been done and how much is left?

I propose we add a progress bar to it?

**Comment by matheusfelipeog** [comment]
Hi @faiqali1 

Thanks for opening this issue

We have some issues with Public APIs, so we won't be able to discuss/implement this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
