### ISSUE TITLE
Shibe.Online CORS is NO

### ISSUE THREAD

**Issue by puddinggggg** [public-apis/public-apis#3125]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

please check it and change.

**Comment by matheusfelipeog** [comment]
Hi @puddinggggg 

Thanks for your contribution ;)

We have some problems with public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
