### ISSUE TITLE
Lyrics api doesnt work

### ISSUE THREAD

**Issue by tashpjak** [public-apis/public-apis#3142]
Hello, 
`https://docs.ksoft.si/api/lyrics-api` doenst work. 
I suggest to remove it from the list

**Comment by matheusfelipeog** [comment]
Hi @tashpjak 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
