### ISSUE TITLE
Add ' API Hubs ' section

### ISSUE THREAD

**Issue by kaustav202** [public-apis/public-apis#3166]
It would be handy if a API Hub section can be added which can include large-scale API repositories/platforms such as rapidAPI.
Those seeking more options can always look up these sites for something extra that's not in this repo.
This would also allow the repo to just feature the most popular / helpful ones, making it more simple and less confusing.

**Comment by matheusfelipeog** [comment]
Hi @kaustav202 

Thanks for your contribution ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104

**Comment by kaustav202** [comment]
It's understandable @matheusfelipeog
