### ISSUE TITLE
GurbaniNow api is not found

### ISSUE THREAD

**Issue by kshtj24** [public-apis/public-apis#3182]
GurbaniNow api is returning a 404 error. [https://github.com/GurbaniNow/api]

**Comment by matheusfelipeog** [comment]
Hi @kshtj24 

Thanks for letting us know ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
