### ISSUE TITLE
Boa tarde, galera.

### ISSUE THREAD

**Issue by Brubru2022** [public-apis/public-apis#3187]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

**Comment by Brubru2022** [comment]
Boa tarde, galera.
Estou precisando de uma API que contém os feriados dos municípios de São Paulo, conseguem me ajudar?

**Comment by rafaelaxmedina** [comment]
Olá, conheço essa API https://api.invertexto.com/api-feriados 

É bem simples de ser aplicada.

**Comment by matheusfelipeog** [comment]
Obrigado pela indicação @rafaelaxmedina ;)

Como já houve uma indicação de API para a sua necessidade @Brubru2022, essa issue será fechada.
