### ISSUE TITLE
MetaWeather Issue

### ISSUE THREAD

**Issue by jevoneBarrett** [public-apis/public-apis#3201]
Hey Community, 
The URL for the MetaWeather API do not work and needs to be fixed.

**Comment by Genius1512** [comment]
According to [this](https://syncwith.com/api/metaweather-api) site, metaweather goes down a lot, so I think the URL is correct, metaweather is just down

**Comment by matheusfelipeog** [comment]
Hi @jevoneBarrett 

Thanks for opening this issue

We have some problem with Public APIs, so we won't be able to discuss/implement this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
