### ISSUE TITLE
Fix typo in Cors field of Tax Data API

### ISSUE THREAD

**Issue by median-man** [public-apis/public-apis#3262]
Note the spelling in the last field. `Unkown` should be `Unknown`

https://github.com/public-apis/public-apis/blob/055f7b0580490a89e8f7e6e61690e5c52f0e8181/README.md?plain=1#L779

**Comment by Nithin1728** [comment]
Hi I'm new to Open Source. Can I work on this issue?

**Comment by median-man** [comment]
> Hi I'm new to Open Source. Can I work on this issue?

Hi @Nithin1728 . Thanks for offering to pitch in. There is already a pull request open for this one. (see #3263 )

**Comment by matheusfelipeog** [comment]
Hi @median-man 

Thanks for opening this issue

We have some problem with Public APIs, so we won't be able to discuss/implement this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
