### ISSUE TITLE
Domain has been suspended

### ISSUE THREAD

**Issue by tarpagad** [public-apis/public-apis#3267]
### Whois veriﬁcation is pending

> Since January 2014, all ICANN accredited registrars (like Namecheap) have been required to verify the contact information (Registrant Whois) of customers registering domain names. This includes modifications to the contact details.

**Comment by pawelborkar** [comment]
> Few days ago, the domains was unreachable. Today, http://public-apis.org/ seems to redirect on the following issue #3104 Is that correct ?

Yes.
