### ISSUE TITLE
Add TraderMade Forex, CFD API under finance apis

### ISSUE THREAD

**Issue by rahulkhn** [public-apis/public-apis#3327]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

**Comment by matheusfelipeog** [comment]
Hi @rahulkhn 

Thanks for opening this issue

We have some problem with Public APIs, so we won't be able to discuss/implement this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
