### ISSUE TITLE
MetaWeather Error 404

### ISSUE THREAD

**Issue by felixrodrigo19** [public-apis/public-apis#3334]
The [MetaWeather](https://www.metaweather.com/api/) API return error 404 when access
Error: Page not found
The requested URL was not found on this server.

**Comment by faradeen-ja** [comment]
#3334

Metaweather API down?  
If meta weather API is down [jump to the section](https://syncwith.com/tutorials/metaweather-api-bMTnC8mp4PxAWCx2m96zhh#MetaWeater_Alternative_Open_Weather_Map) on how to build a weather dashboard without metaweather api.   We’ve been seeing [metaweather.com](http://metaweather.com/) going down a lot so don’t be surprised if you see this too.

**Comment by matheusfelipeog** [comment]
Hi @felixrodrigo19

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
