### ISSUE TITLE
Updates owo.vc's link to point to the correct page for API documentation, as well as updates the link text with the full and more accurate name of the service.

### ISSUE THREAD

**Issue by MistressElla740** [public-apis/public-apis#3345]
Updates owo.vc's link to point to the correct page for API documentation, as well as updates the link text with the full and more accurate name of the service.

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not have more than 100 characters
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

__Originally posted by @katlyn in https://github.com/public-apis/public-apis/pull/3344__

**Comment by matheusfelipeog** [comment]
Hi @MistressElla740 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
