### ISSUE TITLE
Doge API no longer works

### ISSUE THREAD

**Issue by Studio-Hawaii** [public-apis/public-apis#3358]
Doge generation meme domain was sold.
Its no longer around.

**Comment by Chamepp** [comment]
## Issue Description
The Doge Meme Generator(doge-meme.lol) API, located in the social category is no longer available.

## Steps To Reproduce
1. Heading to the social category
2. Click on "[Doge-Meme](https://api.doge-meme.lol/docs)"

## Encounter error page in response:
![Screen Shot 2022-11-25 at 11 05 27 AM](https://user-images.githubusercontent.com/56440241/203926085-a6250d62-2df6-412f-9c9e-e902876de077.png)

## Problem Cause
**Unidentified**

**Comment by AliBilgin35** [comment]
Here you can get training and further your development. [tectrain](https://tectrain.ch/de)

**Comment by matheusfelipeog** [comment]
Hi @Studio-Hawaii 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
