### ISSUE TITLE
Some APIS either shutting down or shut down.

### ISSUE THREAD

**Issue by Studio-Hawaii** [public-apis/public-apis#3362]
Some APIS have shut down and are shutting down.  This is a huge issue for this public APIS list. You should review them and take down ones that say are shutting down or have shut down.

**Comment by mariahlaqua** [comment]
Indeed, since Heroku switched to paid, many of the APIs are no longer functional. It seems that pull requests haven't been merged in quite some time.

**Comment by LUIS9799** [comment]
Try to remove any Heroku-hosted API as it is not working anymore as @mariahlaqua said

**Comment by Jdhjrs** [comment]
Ok man

**Comment by Jdhjrs** [comment]
What is this program

**Comment by matheusfelipeog** [comment]
Hi @Studio-Hawaii 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
