### ISSUE TITLE
anApi is down

### ISSUE THREAD

**Issue by souvik666** [public-apis/public-apis#3376]
[aniApi](https://aniapi.com/docs/)  seems to be down

**Comment by dharmik209** [comment]
Can, I contribute with you guys?

**Comment by matheusfelipeog** [comment]
Hi @souvik666 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104

**Comment by souvik666** [comment]
> Hi @souvik666
> 
> Thanks for opening this issue ;)
> 
> We have some problems with Public APIs, so we won't be able to review/add this improvement right now.
> 
> Read this issue for more information, please: #3104

cool
