### ISSUE TITLE
Api is not working, link is broken

### ISSUE THREAD

**Issue by Boby900** [public-apis/public-apis#3380]
# Bhagavad Gita API is not working
![Screenshot (10)](https://user-images.githubusercontent.com/111265239/208236192-46c2ce02-7035-4f50-8fd6-58347e4fd3c6.png)
[Bhagavad Gita](https://docs.bhagavadgitaapi.in/)

**Comment by jaydeepkhatri** [comment]
Hi @Boby900 
I think this is the correct URL: https://bhagavadgitaapi.in/
Let me know If I am wrong.

Thanks :)

**Comment by Boby900** [comment]
thanks, @jaydeepkhatri 
I realized my mistake
