### ISSUE TITLE
Songsterr API is page not found currently

### ISSUE THREAD

**Issue by AdwaitKulkarni58** [public-apis/public-apis#3382]
Kindly update the Songsterr API link as it is leading to a not found entry currently.

**Comment by matheusfelipeog** [comment]
Hi @AdwaitKulkarni58 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
