### ISSUE TITLE
APIs on Heroku free plans, not working any more...

### ISSUE THREAD

**Issue by amartadey** [public-apis/public-apis#3384]
After heroku shut down their their free tier, multiple APIs have stopped working, Please remove them from this list as they are just dead content.

**Comment by I-Fardeen** [comment]
> After heroku shut down their their free tier, multiple APIs have stopped working, Please remove them from this list as they are just dead content.

Hi, 
Can you mention those APIs?
Thanks

**Comment by amartadey** [comment]
There are a lot of them, Here are the some that i found on the first Animals category itself..

https://theaxolotlapi.netlify.app/
https://dukengn.github.io/Dog-facts-API/
https://docs.thecatapi.com/
https://zoo-animal-api.herokuapp.com/

**Comment by AceKiron** [comment]
Note to the developers of these APIs, repl.it still has a free tier. The AxolotlAPI is currently being hosted there as well.

**Comment by matheusfelipeog** [comment]
Hi @amartadey 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
