### ISSUE TITLE
https://excuser.herokuapp.com/ no longer valid 

### ISSUE THREAD

**Issue by elliotth30** [public-apis/public-apis#3395]
Just noticed the following URL is no longer valid.

**Comment by qrhfz** [comment]
many heroku hosted apis no longer work

**Comment by matheusfelipeog** [comment]
Hi @elliotth30 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
