### ISSUE TITLE
Chuck Norris Database is Down/Deprecated

### ISSUE THREAD

**Issue by SaileshBK** [public-apis/public-apis#3399]
[Chuck Norris Database](http://www.icndb.com/api/) seems to be down or not supported anymore.

**Comment by Patzi275** [comment]
Do it mean that when an api is down, it should be removed ?

**Comment by matheusfelipeog** [comment]
Hi @SaileshBK 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
