### ISSUE TITLE
Headers required for api 

### ISSUE THREAD

**Issue by Poojakalher** [public-apis/public-apis#3436]
How to find required headers for an api of flower in format api/tasks .
When api is running and server have no task/data then it runs successfully and show empty dictionary but when there is some tasks/data on server then it shows error  500:internal server error. How I can solve this issue?

**Comment by muzaffarumarbek** [comment]
Check your front end part. Data keys should be the same with backend.

**Comment by Arzentus** [comment]
Try to host the API in a different place.

**Comment by matheusfelipeog** [comment]
Hi @Poojakalher 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
