### ISSUE TITLE
Axolotl not working

### ISSUE THREAD

**Issue by icepick4** [public-apis/public-apis#3458]
Axolotl api is no longer working : 

![image](https://user-images.githubusercontent.com/82316285/224163022-97f3368f-8f59-419f-b572-903c5f40ad24.png)

**Comment by Arzentus** [comment]
The API creator have taken it down. You can now only look for an alternative.

**Comment by matheusfelipeog** [comment]
Hi @icepick4 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
