### ISSUE TITLE
Including the Joshua Project is NOT cool

### ISSUE THREAD

**Issue by Lucodivo** [public-apis/public-apis#3469]
"Joshua Project is a research initiative seeking to highlight the ethnic people groups of the world with the fewest followers of Christ. This API was developed to provide believers easier access to the Joshua Project's rich data."

With all due respect, the goal of this API is to replace non-Christian cultures with Christianity. It's a colonialist project and shouldn't be promoted.

I understand it's hard to make everyone happy but these APIs should be at least be slightly vetted.

I am not trying to say Christianity is bad. But promoting the replacement of the world's cultures with Christianity is bad. Just as bad as if it were Islam, Judaism, Scientology, or Atheism.

**Comment by tilkinsc** [comment]
That's what religions do. Spread. Promoting the replacement is a bit extreme to say, given they don't depict anything radical about it other than supporting the work of missionaries. The data is invaluable for scientific studies I suppose.

**Comment by Lucodivo** [comment]
That is not what "religions" do. That is what Christianity and Islam does. Most religions have no intentions on replacing the world's culture with their own.

**Comment by tilkinsc** [comment]
Yes, most religions have a desire to spread their beliefs and teachings to others. The reasons for this can vary depending on the specific religion, but some common motivations include a belief in the importance of sharing the truth, a desire to bring spiritual salvation or enlightenment to others, and a sense of responsibility to fulfill the mission or commandments given by their deity or religious texts.

Different religions employ various methods to spread their teachings. Some common approaches include:

    Missionary work: Many religions have missionaries who actively go out to share their faith with others. These missionaries may engage in activities such as preaching, teaching, and providing social services to communities.

    Proselytization: This involves actively seeking converts to the religion and persuading individuals to adopt its beliefs and practices.

    Religious texts and literature: Religions often produce sacred texts and religious literature that serve as guides for believers and can be shared with others to spread their teachings.

    Public worship and rituals: Public religious ceremonies, worship services, and rituals can serve as opportunities to expose people to a particular religion and its practices.

    Media and technology: In the modern era, religions may use media platforms, such as television, radio, the internet, and social media, to reach a wider audience and disseminate their messages.

It's important to note that the methods and extent of religious propagation can vary among different religious traditions and individual adherents. While many religions actively seek to spread their faith, there are also religions and spiritual paths that prioritize personal spiritual growth and do not actively engage in proselytization.

**Comment by Lucodivo** [comment]
Show me the API for Hindu missionaries.

**Comment by Lucodivo** [comment]
I do not wish to speak with ChatGPT.

**Comment by matheusfelipeog** [comment]
Hi @Lucodivo 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
