### ISSUE TITLE
LAPIS is not documented

### ISSUE THREAD

**Issue by Patzi275** [public-apis/public-apis#3470]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

**Comment by matheusfelipeog** [comment]
Hi @Patzi275 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104

**Comment by Patzi275** [comment]
Thanks
