### ISSUE TITLE
API is deprecated

### ISSUE THREAD

**Issue by TechWithTy** [public-apis/public-apis#3472]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

Most of the links are years old, broken. some items just open pictures instead of going to the site...

**Comment by Gourav2580** [comment]
please assignees

**Comment by Luckytrash77716v** [comment]
Fine

**Comment by matheusfelipeog** [comment]
Hi @TechWithTy 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
