### ISSUE TITLE
Excuser API dosen't work 

### ISSUE THREAD

**Issue by Aniyo44** [public-apis/public-apis#3517]
![exuser](https://github.com/public-apis/public-apis/assets/109015835/708a5e12-c538-4543-ba89-edc7c3ef137d)

**Comment by Mayuresh-22** [comment]
Hey, @Aniyo44 Thank You for opening an issue it seems that they have moved their website to a new domain. 
I am working on it and will make the PR.
Thank You.

**Comment by jatinxkirito** [comment]
That API is just pulling some random ads now. Please avoid using it for a while

**Comment by matheusfelipeog** [comment]
Hi @Aniyo44 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
