### ISSUE TITLE
https://api.creativecommons.engineering/

### ISSUE THREAD

**Issue by Stedawg91** [public-apis/public-apis#3539]
Broken link

**Comment by abhishekgite446** [comment]
Hi @Stedawg91, thanks for the issue.

I suppose you are talking about the following highlighted link. The link doesn't seem to be broken as it redirects to https://api.openverse.engineering/v1/ . Based on the [news article](https://creativecommons.org/2021/12/13/dear-users-of-cc-search-welcome-to-openverse/) I believe this is the correct behaviour.

![image](https://github.com/public-apis/public-apis/assets/253690/96e749c5-cd50-4be6-a65f-55a34611d5b0)

**Comment by matheusfelipeog** [comment]
Hi @Stedawg91 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
