### ISSUE TITLE
unfettered.codes

### ISSUE THREAD

**Issue by Abhay557** [public-apis/public-apis#3547]
i have made multipurpose api!
i have issue that it contain anime, fun, fake data, animals images , news endpoints so where i add api in this repo!
please add my api!
| API | Description | Auth | HTTPS | CORS |
| --- | --- | --- | --- | --- |
| [unfettered](https://unfettered.codes) | unfettered a multipurpose api  | No | Yes | No |

**Comment by Abhay557** [comment]
i have just completed its documentation i will host it on main website

**Comment by matheusfelipeog** [comment]
Hi @Abhay557 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
