### ISSUE TITLE
Include usage of API specifications

### ISSUE THREAD

**Issue by gregsdennis** [public-apis/public-apis#3559]
First of all, fantastic list!

I think it would be great to include the type of API along with any specifications they follow, e.g. Swagger/OpenAPI (which version), AsyncAPI, GraphQL, etc.

I find myself needing examples of APIs that use each of these, and having that as a column in the list would be a great help!

Thanks!

**Comment by dharmik209** [comment]
Can, I contribute to this repo?

**Comment by mianshahzadmushtaq** [comment]
Sent from Yahoo Mail on Android 
 
  On Tue, Aug 8, 2023 at 9:07 PM, Yug ***@***.***> wrote:   


Can, I contribute to this repo?

**Comment by matheusfelipeog** [comment]
Hi @gregsdennis 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
