### ISSUE TITLE
time door API gives me random ads

### ISSUE THREAD

**Issue by wkCircle** [public-apis/public-apis#3573]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

I try to find time series related API, but found that the API called time door is no longer useful since it always open a random ads. 
Should this API be removed?

**Comment by matheusfelipeog** [comment]
Hi @wkCircle 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
