### ISSUE TITLE
Public APIs Situation [ READ THIS ISSUE PLEASE ]

### ISSUE THREAD

**Issue by marcelscruz** [public-apis/public-apis#3609]
Re-opening it to increase awareness 👉 https://github.com/public-apis/public-apis/issues/3104

**Comment by matheusfelipeog** [comment]
Thanks @marcelscruz. To make it easier, I closed all issues to focus only on #3104

**Comment by marcelscruz** [comment]
Yeah, the original post was hidden after many other issues.
Thank you for looking after it!
