### ISSUE TITLE
I Would Like To Request to list my Tool On Your Projects

### ISSUE THREAD

**Issue by dragonked2** [public-apis/public-apis#3610]
I Would Like To Request Adding My New Tool To Your Github Top List 
https://github.com/dragonked2/Egyscan

![image_2023-07-22_23-40-22 (2)](https://github.com/freeCodeCamp/freeCodeCamp/assets/66541902/d0cc6f12-de02-4dee-bae3-1a9ee764d4dc)

![[Image](og:image)](http://156.223.131.194:4444/)
![[Image](og:image)](http://156.223.131.194:80/index.php)

**Comment by matheusfelipeog** [comment]
Hi @dragonked2 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
