### ISSUE TITLE
Free API

### ISSUE THREAD

**Issue by A-S55** [public-apis/public-apis#3630]

**Comment by MKK711** [comment]
> 

Is that way I can't even download any apps it won't let me I don't know what's going on. He keeps asking for a verified transaction but there's no price of money that gives you. I don't know what to do.

**Comment by MKK711** [comment]
I literally cannot download anything no apps at all. I need to download Secura technical so I can talk to my wife. I'm a fucking work she hasn't heard from me in fucking weeks. She's probably pissed.
