### ISSUE TITLE
Missing and viruses

### ISSUE THREAD

**Issue by ktannehill** [public-apis/public-apis#3660]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

The Excuser API was not present, and the Fun Fact API gave me a virus

**Comment by matheusfelipeog** [comment]
Thanks @ktannehill, but this is a duplicate: #3384 #3432

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
