### ISSUE TITLE
Free image generation API

### ISSUE THREAD

**Issue by Metim0l** [public-apis/public-apis#3668]
Good day! I've created my own completely free image generation api. Thought you might be interested in adding it to your list. Here is the link: https://github.com/Metim0l/VisionCraft

**Comment by matheusfelipeog** [comment]
Hi @Metim0l 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
