### ISSUE TITLE
Adding a rating (staring)

### ISSUE THREAD

**Issue by daveragos** [public-apis/public-apis#3704]
adding some kinda **rating** or **star counting** on each _api_
and the users then would give it a star or a rate depending on their experience of the api

**Comment by matheusfelipeog** [comment]
Hi @daveragos 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
