### ISSUE TITLE
Adding Quote API to your collection

### ISSUE THREAD

**Issue by Enesjashari** [public-apis/public-apis#3717]
Hi!

I want to add my API project to your collection , I've just talk to one of contributors of this repository and his response was ,Right now we have some problems but make an issue and as soon as we fix our problems I will add your project in API collection

https://quoteapi.pythonanywhere.com/

Thanks,
Enes

**Comment by matheusfelipeog** [comment]
Hi @Enesjashari 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
