### ISSUE TITLE
Plz accept my pr#3721

### ISSUE THREAD

**Issue by dubeychandan996** [public-apis/public-apis#3732]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

Is this repo dead?

**Comment by matheusfelipeog** [comment]
Hi @dubeychandan996 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
