### ISSUE TITLE
Not Working -- Anime > AniAPI

### ISSUE THREAD

**Issue by sumit-coder** [public-apis/public-apis#3741]
The AniApi in Anime website is not working, maybe need to remove it,

https://github.com/public-apis/public-apis/assets/55745378/877f4f13-1942-4688-bbf8-3b22b4221a73

**Comment by matheusfelipeog** [comment]
Hi @sumit-coder 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104

**Comment by sumit-coder** [comment]
Okay,
