### ISSUE TITLE
Adding a new category.

### ISSUE THREAD

**Issue by rjb4standards** [public-apis/public-apis#3768]
Is there a way for a party to request that one of the existing maintainers add a new category "Trusted Product Labels" to list the API's providing access to trust labels, such as the EU CE mark and US Trust Mark. i.e.
https://softwareassuranceguardian.com/SAGCTR_inquiry/getUSTRustLabel?ProductID={id} 

Thanks,
Dick Brooks

**Comment by FFUV** [comment]
Take this down 
basically the creators of this are abusing  their power and arent treating people who help contribute and maintain the project so unlike this unstar this star ny fork of this that doesnt support this one 
#3104

**Comment by matheusfelipeog** [comment]
Hi @rjb4standards 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
