### ISSUE TITLE
Adding financial APIs- EODHD API and BitMart API

### ISSUE THREAD

**Issue by Akshat111111** [public-apis/public-apis#3772]
I want to add these APIs in the financial API collection .Kindly assign me this issue.

**Comment by FFUV** [comment]
Take this down 
basically the creators of this are abusing  their power and arent treating people who help contribute and maintain the project so unlike this unstar this star ny fork of this that doesnt support this one 
#3104 
#3484

**Comment by Akshat111111** [comment]
Sure
