### ISSUE TITLE
Adding BBC News API

### ISSUE THREAD

**Issue by Sayad-Uddin-Tahsin** [public-apis/public-apis#3778]
BBC News API is an API for serving BBC News in JSON. It has a wide range of 29 various languages.

API Repository: https://github.com/Sayad-Uddin-Tahsin/BBC-News-API
API Endpoint: https://bbc-api.vercel.app
API Documentation: https://bbc-api.vercel.app/doc

**Comment by FFUV** [comment]
Take this down 
basically the creators of this are abusing  their power and arent treating people who help contribute and maintain the project so unlike this unstar this star ny fork of this that doesnt support this one 
#3104

**Comment by matheusfelipeog** [comment]
Hi @Sayad-Uddin-Tahsin 

Thanks for opening this issue ;)

We have some problems with Public APIs, so we won't be able to review/add this improvement right now.

Read this issue for more information, please: https://github.com/public-apis/public-apis/issues/3104
