### ISSUE TITLE
Why is `client_secret` compulsory int he following requests ?

### ISSUE THREAD

**Issue by maru9990** [public-apis/public-apis#3822]
Why is `client_secret` compulsory int he following requests ?

According to the OAuth specs, it shouldn't be...

This fails
```
POST https://api.oauth2server.com/token
grant_type=password&
username=username&
password=password&
client_id=client_id
```

Same for implicit grants...

```
{
    "error": "invalid_client",
    "error_description": "The client credentials are invalid"
}
```

_オリジナルは @adadgio が https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/473 にポスト_

**Comment by ahmedjanwar** [comment]
The error you're encountering, "invalid_client", suggests that the client credentials you're providing are not being accepted by the OAuth2 server. While in the OAuth2 specification, client_secret is not always required (it depends on the grant type and server configuration), it seems that in the case you're experiencing, the server you're interacting with requires the client_secret.
