### ISSUE TITLE
Feature Request: Add OpenAPI spec

### ISSUE THREAD

**Issue by Astoria-Deville** [public-apis/public-apis#3842]
Some application interfaces are inaccurately described, which may be due to multiple versions or feature extensions.Many public APIs exposes an OpenAPI file that can be used to help use the APIs.Some of the generic categories, such as auth, https, and cors, are not user-friendly, and perhaps they could be replaced with more specific interface addresses.

**Comment by Astoria-Deville** [comment]
We will help out this week. If anyone also like to help, this site will be useful: https://apis.guru/

**Comment by Fooooooooool** [comment]
Well done!

**Comment by JAHSON996** [comment]
Thnkx
