### ISSUE TITLE
Add API base URLs

### ISSUE THREAD

**Issue by pimterry** [public-apis/public-apis#883]
It'd be useful to have the base URLs for each API listed (e.g. all Trello requests start with `https://api.trello.com/1`).

That would make it possible to do reverse lookups, and use this list to find docs, descriptions & metadata for a given URL or HTTP request, rather than just finding APIs by category. It'd take a fair bit of manual work to fill out, but I think it'd be super useful. Is that something you'd be open to?

**Comment by yannbertrand** [comment]
Hey! Sorry for the delay

I'm not sure on how that would be helpful. Can you help me to understand why?
Don't you think that would be too complicated to have all those information in here?

**Comment by yannbertrand** [comment]
See #1055
