### ISSUE TITLE
Petfinder might be dead, or at least the link is dead

### ISSUE THREAD

**Issue by PressX2Jason** [public-apis/public-apis#913]
The [link](https://www.petfinder.com/developers/api-docs/) provided in the readme for petfinder now leads to a redirect site instead of the api.

**Comment by mloberg** [comment]
See #911

**Comment by riderjensen** [comment]
Both the old doc and new doc links are 404ing with Travis, not sure what the issue is - see https://github.com/toddmotto/public-apis/pull/926
