### ISSUE TITLE
[Idea/Enhancement] Adding link to python module

### ISSUE THREAD

**Issue by navanchauhan** [public-apis/public-apis#950]
Most of the API links have wrappers around them, why don't we start including them?

**Comment by yannbertrand** [comment]
Hey! Sorry for the delay

What do you mean by wrappers?

**Comment by Tadaboody** [comment]
I think they mean something like what [discord.py](https://discordpy.readthedocs.io/en/latest/) is for the discord api

**Comment by yannbertrand** [comment]
I see. The point of this repo is to give the "lower level" API which can be used with no wrapper at all if wanted. I understand why it would be useful but it would be too much maintaining work.

I would suggest adding these wrappers info directly inside the API documentations if possible.
