### ISSUE TITLE
This is one of my favorite repositories for awesome APIs

### ISSUE THREAD

**Issue by inglesuniversal** [public-apis/public-apis#994]
Would you suggest or add something I see missing:

form generators for developers

there are hundreds out there, I hope you can help me narrow down my options and better yet, include it for the benefit of other developers.

Regards

**Comment by yannbertrand** [comment]
Hey!

I'm not sure on what you are talking about, what do you mean by form generators?

**Comment by inglesuniversal** [comment]
Like this one:

https://formbuilder.online/

**Comment by yannbertrand** [comment]
I see... Well this repo is not suited for that since we are listing Public HTTP(s) APIs but you could certainly create another repo for those! 😃
