### ISSUE TITLE
fortniteapi.com important information

### ISSUE THREAD

**Issue by stl1988** [public-apis/public-apis#998]
Starting September 1st, the Fortnite API at fortniteapi.com will always require an authorization token, even on the "public" server. The developer has announced this on the Discord server of this API.

**Comment by montogeek** [comment]
Should we remove it?

**Comment by stl1988** [comment]
No, but the table always says if an authorization is required, and that should be changed from "No" to "apiKey" at Sepzember 1st. The API is still freely available.
